{
 "title": "Acquisition passes status (from EDRS)",
 "tags": [ "Acquisition" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_id\", \"query\":\"mission:$mission\"}"
   },
   {
    "name": "link_session_id",
    "label": "Link_session_id",
    "query": "{\"find\": \"terms\", \"size\": 10000,\"field\": \"link_session_id\", \"query\": \"satellite_id:$satellite_unit AND geo_satellite_id:$geo_satellite_id\"}"
   },
   {
    "name": "geo_satellite_id",
    "label": "Geo Satellite ",
    "query": "{\"find\": \"terms\", \"field\": \"geo_satellite_id\", \"query\": \"satellite_id:$satellite_unit\"}"
   },
   {
    "name": "ground_station",
    "label": "Ground Station",
    "query": "{\"find\": \"terms\", \"field\": \"ground_station\", \"query\": \"satellite_id:$satellite_unit AND geo_satellite_id:$geo_satellite_id\"}"
   },
   { "name": "planned_link_session_start", "label": "Planned_link_session_start", "query": { "query": "" } },
   { "name": "planned_link_session_stop", "label": "Planned_link_session_stop", "query": { "query": "" } },
   { "name": "datatake_id", "label": "Datatake", "query": { "query": "" } },
   { "name": "mission_edrs", "label": "Mission_edrs", "query": { "query": "" } },
   {
    "name": "report_type",
    "label": "Report Type",
    "query": "{\"find\": \"terms\", \"field\": \"report_type\"}"
   },
   { "name": "acquisition_filter", "label": "AcquisitionFilters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Acquisition passes status.\n\nInformation is available for the following missions: S1 and S2.\n\nThe information displayed was originally taken from EDRS Report Ticket at JIRA EDRS  \n\nTime reference for this dashboard is : planned_link_session_start\n\nReport Type Logic : \n- If a document has been extracted from a daily report but not from a weekly or monthly report, it will be visible if 'daily' is selected\n- If a document has been extracted from a weekly report but not from a monthly report, il will be visible if 'weekly' is selected\n- If the same document has been extracted from multiple source, it will be available through the best source. Eg: To see a document retrieved from a weekly and a monthly source, you have to select 'monthly'\n- 2 document are considered equal for the report_type logic if they have the same link_session_id and the same ground_station\n- It is possible to find where the document originate from through the field 'report_name_daily' 'report_name_weekly' and 'report_name_monthly'\n\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Station Acquisition Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Success Linked Session Acquisition Status ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND NOT total_status: \"NOK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "All Link Session Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "link_session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Failed Link Session Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "link_session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND total_status: \"NOK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Success Link Session Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "link_session_id", "id": "1", "type": "cardinality" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND NOT total_status: \"NOK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Success Station Acquisition Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND  total_status: \"OK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "All Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Failed Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND NOT total_status: \"OK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Success Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND total_status: \"OK\" AND report_type:$report_type",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Acquisition passes status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Acquisition Passes Status Timeline by ground station",
     "type": "marcusolsson-gantt-panel",
     "description": "in green when both sucess |\nIn yellow when the station sucess but the other failed |\nin orange when the station failed but the other sucess  |\nin red when both failed",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
       "timeField": "planned_link_session_start"
      }
     ]
    },
    {
     "title": "Acquisition Passes Status ",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id AND report_type:$report_type",
       "timeField": "planned_link_session_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Planned Downlinks And Datatake Completeness Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=mission:$mission_edrs AND station:$geo_satellite_id AND effective_downlink_start:[0 TO ${planned_link_session_stop}] AND effective_downlink_stop:[${planned_link_session_start} TO *]&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "S1 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S1 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "S2 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S2 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  }
 ]
}