{
 "title": "Station Acquisition Status (CADIP)",
 "tags": [ "Acquisition" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\",\"query\":\"mission: *\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_id\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "ground_station",
    "label": "Reception Station",
    "query": "{\"find\": \"terms\", \"field\": \"ground_station\",\"query\":\"mission:$mission AND satellite_id:$satellite\"}"
   },
   {
    "name": "downlink_orbit",
    "label": "Downlink Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"downlink_orbit\",\"query\":\"mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station\"}"
   },
   { "name": "datatake_id", "label": "Datatake_id", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Downlink Acquisition status.\n\nThe information displayed was originally taken from Session with Quality Infos at each CADIP station  \n\nMPS: Maspalomas  \nINS/INU: Inuvik (INU is for S5p, INS for S2)  \nNSG: Neustrelitz  \nMTI: Matera  \nSGS: Svalbard  \n\nInformation is taken from station reports made available through CADIP interface.\n\nInformation is available for the following missions: S1, S2 and S3.\n\nTime reference for this dashboard is : planned_data_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Station Acquisition Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Failed FER Data Check",
   "type": "stat",
   "description": "Success Station with FER Data > 10e-6\nThis should be null",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: OK AND fer_data: [0.000001 TO *]",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Success Acquisition Status ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: OK",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "All Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND  NOT global_status: INCOMPLETE",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Failed Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: NOK",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Success Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: OK",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Success Acquisition Status by Station",
   "type": "gauge",
   "description": "global_status: OK AND from_acq_delivery_timeliness: [* TO 43200000000] (12h) ",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      {
       "field": "ground_station",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "othercount",
       "id": "1",
       "meta": {
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": true
       },
       "settings": { "missing": "1" },
       "type": "extended_stats"
      }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: OK AND from_acq_delivery_timeliness: [* TO 43200000000]",
     "timeField": "planned_data_start"
    },
    {
     "alias": "All Station Acquisition Status ",
     "bucketAggs": [
      {
       "field": "ground_station",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND NOT global_status: INCOMPLETE",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Incomplete Acquisition Status ",
   "type": "stat",
   "description": "Sometime some mandatory data is missing inside the CADIP Session (date or status)\n\nWe use publication_date as time reference\n\nWe don't include incomplete pass in completeness",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-cadip-acquisition-pass-status/_search?q=mission:${mission:lucene} AND satellite_id:${satellite:lucene} AND ground_station:${ground_station:lucene} AND downlink_orbit:${downlink_orbit:lucene} AND global_status: INCOMPLETE AND publication_date: [${__from} TO ${__to}]",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Acquisition Timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "panelId": 47 }
   ]
  },
  {
   "title": "Acquisitions Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Incomplete Session - Details",
   "type": "table",
   "description": "Sometime some mandatory data is missing inside the CADIP Session (date or status)\nWe use publication_date as time reference",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-cadip-acquisition-pass-status/_search?q=mission:${mission:lucene} AND satellite_id:${satellite:lucene} AND ground_station:${ground_station:lucene} AND downlink_orbit:${downlink_orbit:lucene} AND global_status: INCOMPLETE AND publication_date: [${__from} TO ${__to}]",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "FER failed check - Details",
   "type": "table",
   "description": "Success Station with FER Data > 10e-6\nThis table should be empty",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND global_status: OK AND fer_data: [0.000001 TO *]",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Delivery bitrate details ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average bitrate per station",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "ground_station",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "planned_data_start",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "avg" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Lowest bitrate per orbit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "downlink_orbit",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "5" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "min" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "3 Lowest downlink orbit bitrate per station",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "ground_station",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "downlink_orbit",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "3" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "min" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Lowest bitrate per station",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "ground_station",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "min" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Lowest average bitrate per orbit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "downlink_orbit",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "4", "size": "5" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "4", "type": "avg" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Average bitrate per station",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "ground_station",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "avg" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Highest bitrate per orbit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "downlink_orbit",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "5" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "3", "type": "max" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    },
    {
     "title": "Highest bitrate per station",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "All Station Acquisition Status ",
       "bucketAggs": [
        {
         "field": "ground_station",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "delivery_bitrate", "id": "1", "type": "max" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Acquisition details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Detailed Acquisition Table",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
       "timeField": "planned_data_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Planned Downlinks And Datatake Completeness Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
     "options": {
      "content": "To view planned downlinks and associated datatake, please select downlink orbit on acquisition table."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=station:*${ground_station}* AND downlink_absolute_orbit:${downlink_orbit}&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "S1 Datatake",
     "type": "table",
     "description": "WARNING : This panel is indexed by observation_time_start and not planned_data_start. Please widen the time period if you see no datatakes when you should.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S1 AND datatake_id:${datatake_id}",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "S2 Datatake",
     "type": "table",
     "description": "WARNING : This panel is indexed by observation_time_start and not planned_data_start. Please widen the time period if you see no datatakes when you should.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S2 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  }
 ]
}