{
 "title": "Station Acquisition Status (X-Band)",
 "tags": [ "Acquisition" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\",\"query\":\"mission: *\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_id\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "ground_station",
    "label": "Reception Station",
    "query": "{\"find\": \"terms\", \"field\": \"ground_station\",\"query\":\"mission:$mission AND satellite_id:$satellite\"}"
   },
   {
    "name": "downlink_orbit",
    "label": "Downlink Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"downlink_orbit\",\"query\":\"mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station\"}"
   },
   { "name": "datatake_id", "label": "Datatake_id", "query": { "query": "" } },
   {
    "name": "report_type",
    "label": "Report Type",
    "query": "{\"find\": \"terms\", \"field\": \"report_type\"}"
   },
   { "name": "Filters", "label": "Acquisition Filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Downlink Acquisition status.\n\nThe information displayed was originally taken from daily DDP report at each WebDAV station (ApsProduct Station)  \n\nMPS: Maspalomas  \nINS/INU: Inuvik (INU is for S5p, INS for S2)  \nNSG: Neustrelitz  \nMTI: Matera  \nSGS: Svalbard  \n\nInformation is taken from station reports made available through XBAND interface.\n\nInformation is available for the following missions: S1, S2, S3 and S5\n\nTime reference for this dashboard is : planned_data_start\n\nReport Type Logic : \n- If a document has been extracted from a daily report but not from a weekly or monthly report, it will be visible if 'daily' is selected\n- If a document has been extracted from a weekly report but not from a monthly report, il will be visible if 'weekly' is selected\n- If the same document has been extracted from multiple source, it will be available through the best source. Eg: To see a document retrieved from a weekly and a monthly source, you have to select 'monthly'\n- 2 document are considered equal for the report_type logic if they have the same link_session_id and the same ground_station\n- It is possible to find where the document originate from through the field 'report_name_daily' 'report_name_weekly' and 'report_name_monthly'\n- Report Type Monthly and Weekly are available only for S5\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Station Acquisition Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Success Station Acquisition Status ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type AND ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "All Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Failed Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type AND NOT ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Success Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type AND ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Acquisition Timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Acquisitions Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND report_type:$report_type",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Planned Downlinks And Datatake Completeness Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "To view planned downlinks and associated datatake, please select downlink orbit on acquisition table."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=station:*${ground_station}* AND downlink_absolute_orbit:${downlink_orbit}&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "S1 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S1 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "S2 Datatake",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S2 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "details",
     "type": "table",
     "description": "If the dashboard is empty keep deploy previous row with the Acquisitions Table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "panelId": 3 }
     ]
    }
   ]
  }
 ]
}