{
 "title": "ADG Completeness (vs external providers) - v2",
 "description": "Support group by external provider",
 "tags": [ "Completeness" ],
 "time": { "from": "now-8d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3" },
   { "name": "auxiliary_data_providers", "label": "Auxiliary Data Providers", "query": { "query": "" } },
   { "name": "product_types", "label": "Product Types", "query": { "query": "" } },
   { "name": "daily_expected_products", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Description",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a completeness by product_type between product published at AUXIP and theorical daily production\n\nDetails of theorical production used in dashboard :\n\nS1:```json[{'product_type': 'AUX_WND', 'product_type_expected': 182.0, 'timeliness': '10 min'}, {'product_type': 'AUX_ICE', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'AUX_TEC', 'product_type_expected': 1.0, 'timeliness': 'N/A'}, {'product_type': 'AUX_TRO', 'product_type_expected': 4.0, 'timeliness': '30 min'}, {'product_type': 'MPL_ORBPRE', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'MPL_ORBRES', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'MPL_TLEPRE', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_B', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_C', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_D', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_E', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_F', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'AUX_PREORB', 'product_type_expected': 14.0, 'timeliness': '10 min'}, {'product_type': 'AUX_RESORB', 'product_type_expected': 14.0, 'timeliness': '10 min'}, {'product_type': 'AUX_POEORB', 'product_type_expected': 1.0, 'timeliness': '10 min'}]```\n\nS2:```json[{'product_type': 'AUX_ECMWFD', 'product_type_expected': 2.0, 'timeliness': '10 min'}, {'product_type': 'AUX_CAMSFO', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'AUX_UT1UTC', 'product_type_expected': 0.14285714285714285, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_A', 'product_type_expected': 6.0, 'timeliness': '30 min'}, {'product_type': 'TLM__REQ_B', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'REP__CHF__', 'product_type_expected': 0.28571428571, 'timeliness': '30 min'}, {'product_type': 'REP__FCHF_', 'product_type_expected': 0.28571428571, 'timeliness': '30 min'}, {'product_type': 'MPL_ORBPRE', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'MPL_ORBRES', 'product_type_expected': 2.0, 'timeliness': '30 min'}]```\n\nS3:```json[{'product_type': 'AX___MF1_AX', 'product_type_expected': 8.0, 'timeliness': '10 min'}, {'product_type': 'AX___MFA_AX', 'product_type_expected': 4.0, 'timeliness': '10 min'}, {'product_type': 'AX___MA1_AX', 'product_type_expected': 4.0, 'timeliness': '10 min'}, {'product_type': 'AX___MF2_AX', 'product_type_expected': 8.0, 'timeliness': '10 min'}, {'product_type': 'AX___MA2_AX', 'product_type_expected': 4.0, 'timeliness': '10 min'}, {'product_type': 'SR___MDO_AX', 'product_type_expected': 2.0, 'timeliness': '10 min'}, {'product_type': 'SR_2_PMPSAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_RMO_AX', 'product_type_expected': 4.0, 'timeliness': '10 min'}, {'product_type': 'SR_2_PMO_AX', 'product_type_expected': 4.0, 'timeliness': '10 min'}, {'product_type': 'SR_2_POL_AX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_PGI_AX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_RGI_AX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_1_USO_AX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR___MGNSAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SL_2_SSTAAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'SL_2_DIMSAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'AX___FPO_AX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'AX___FRO_AX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_PCPPAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_PMPPAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR___MGNPAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR___POEPAX', 'product_type_expected': 2.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_SIFNAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_SIFSAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_SICNAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}, {'product_type': 'SR_2_SICSAX', 'product_type_expected': 1.0, 'timeliness': '30 min'}]```\n\n\n\nTime reference for this dashboard is : publication_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  {
   "title": "Global product type per mission - $mission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "mission"
  },
  {
   "title": "$mission over period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: $mission AND product_type: ${product_types:lucene}",
     "timeField": "publication_date"
    },
    {
     "columns": [
      { "selector": "_source.expected_daily", "text": "expected_daily", "type": "number" },
      { "selector": "_source.product_type", "text": "product_type", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-auxiliary-data-producers-conf/_search",
     "url_options": {
      "data": "",
      "headers": [],
      "method": "GET",
      "params": [
       {
        "key": "q",
        "value": "mission:${mission:lucene} AND product_type:${product_types:lucene}"
       },
       { "key": "size", "value": "9999" }
      ]
     }
    }
   ]
  },
  {
   "title": "$mission over period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: $mission AND product_type: ${product_types:lucene}",
     "timeField": "publication_date"
    },
    {
     "columns": [
      { "selector": "_source.expected_daily", "text": "expected_daily", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "", "text": "", "type": "string" }
     ],
     "json_options": {
      "columnar": false,
      "root_is_not_array": false
     },
     "pagination_mode": "none",
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-auxiliary-data-producers-conf/_search",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       {
        "key": "q",
        "value": "mission:${mission:lucene} AND product_type:${product_types:lucene}"
       },
       { "key": "size", "value": "9999" }
      ]
     }
    }
   ]
  },
  {
   "title": "$mission per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "publication_date",
       "id": "5",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: $mission AND product_type: ${product_types:lucene}",
     "timeField": "publication_date"
    }
   ]
  },
  { "title": "Details for ${product_types}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "product_types" },
  {
   "title": "${product_types} over period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: S1 AND product_type: ${product_types}",
     "timeField": "publication_date"
    },
    {
     "columns": [
      { "selector": "_source.expected_daily", "text": "expected_daily", "type": "number" },
      { "selector": "_source.product_type", "text": "product_type", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-auxiliary-data-producers-conf/_search",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       {
        "key": "q",
        "value": "mission:${mission:lucene} AND product_type:${product_types:lucene}"
       },
       { "key": "size", "value": "9999" }
      ]
     }
    }
   ]
  },
  {
   "title": "${product_types} over period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: $mission AND product_type: ${product_types}",
     "timeField": "publication_date"
    },
    {
     "columns": [
      { "selector": "_source.expected_daily", "text": "expected_daily", "type": "number" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-auxiliary-data-producers-conf/_search",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       {
        "key": "q",
        "value": "mission:${mission:lucene} AND product_type:${product_types:lucene}"
       },
       { "key": "size", "value": "9999" }
      ]
     }
    }
   ]
  },
  {
   "title": "${product_types} per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type: AUXIP AND mission: S1 AND product_type: ${product_types}",
     "timeField": "publication_date"
    },
    {
     "columns": [
      { "selector": "_source.expected_daily", "text": "expected_daily", "type": "number" },
      { "selector": "_source.product_type", "text": "product_type", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-auxiliary-data-producers-conf/_search",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       {
        "key": "q",
        "value": "mission:${mission:lucene} AND product_type:${product_types:lucene}"
       },
       { "key": "size", "value": "9999" }
      ]
     }
    }
   ]
  }
 ]
}