{
 "title": "PRIP-DD Completeness (product count)",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"satellite_unit: ${satellite_unit} \"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\":\"terms\",\"field\":\"product_level\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\":\"terms\",\"field\":\"product_type\",\"query\":\"mission: ${mission} AND product_level: ${product_level}\"}"
   },
   {
    "name": "datatake",
    "label": "Datatake",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND  product_level: $product_level AND product_type:$product_type AND prip_publication_date:* AND timeliness : $timeliness\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Help",
     "type": "text",
     "description": "Proposed AUX Product type list : SR___MGNSAX, SR___ROE_AX, SR_1_CAL___, MW_1_CAL___, OL_1_RAC___\nAUX_CAMSFO, AUX_ECMWFD, AUX_ICE_V2, AUX_PREORB, AUX_RESORB, AUX_SADATA, AUX_TRO_V2, AUX_UT1UTC, AUX_WAV_V2, AUX_WND_V2, AX___FPO_AX, AX___FRO_AX, AX___MA1_AX, AX___MA2_AX, AX___MF1_AX, AX___MF2_AX, AX___MFA_AX, GN_1_GCLHAX, GN_1_GSVHAX, GN_1_GSVMAX, GN_1_MASSAX, GN_1_NAV_AX, GN_1_SAC_AX, MW_1_CAL___, OL_1_RAC___, PRD_HKTM__, SL_1_VSC_AX, SL_2_DIMSAX, SL_2_SSTAAX, SR_1_CAL___, SR_2_NRPPAX, SR_2_PGI_AX, SR_2_PMO_AX, SR_2_PMPPAX, SR_2_PMPSAX, SR_2_RGI_AX, SR___MDO_AX, SR___MGNPAX, SR___MGNSAX, SR___ROE_AX, OPER_AUX_P, OPER_AUX_R<br>",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard compares products Disseminated at the DHUS with against Products Published at PRIP.\n\n\nThe information displayed was originally taken from Product at PRIP DD  \n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Products published @PRIP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND  product_level: $product_level AND product_type:$product_type AND prip_publication_date:* AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Products published @DHUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND  product_level: $product_level AND product_type:$product_type  AND ((mission: S2 AND ddip_id:*) OR ( NOT mission: S2 AND ddip_name:*)) AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Products published @PRIP and @DHUS per product type",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND product_level: $product_level AND product_type:$product_type AND prip_publication_date:* AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    },
    {
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND product_level: $product_level AND product_type:$product_type AND ((mission: S2 AND ddip_id:*) OR ( NOT mission: S2 AND ddip_name:*)) AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Product list @PRIP and @DHUS",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND product_level: $product_level AND product_type:$product_type AND ((mission: S2 AND ddip_id:*) OR ( NOT mission: S2 AND ddip_name:*)) AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    },
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite_unit AND product_level: $product_level AND product_type:$product_type AND prip_id:* AND timeliness : $timeliness AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  }
 ]
}