#! /bin/bash

source ./functions.sh

export omcs_ENV_SETTED="True"
export PYTHON_VERSION="3.11"
export WORK_DIR=$(pwd)
export LOGS_DIR=${WORK_DIR}/logs
export VENV_NAME=omcs-venv
export VENV_PATH=${WORK_DIR}/${VENV_NAME}
export ES_USERNAME=admin
export ES_PASSWORD=admin
export ES_PORT=9200
export ES_URL=https://localhost:${ES_PORT}/
export AMQP_PORT=5672
export AMQP_IHM_PORT=15672
export AMQP_URL=amqp://localhost:${AMQP_PORT}//
export AMQP_USERNAME=guest
export AMQP_PASSWORD=guest
export GRF_PORT=3000
export HEALTHCHECK_HOSTNAME=0.0.0.0
export INITDB_HEALTH_PORT=49250
export ENGINE_HEALTH_PORT=49251
export COLLECTOR_HEALTH_PORT=49252
export CDS_TAG_VERSION=2.4.1
export COLLECTOR_TAG_VERSION=3.5.1

msg "omcs_ENV_SETTED=${omcs_ENV_SETTED}"
msg "PYTHON_VERSION=${PYTHON_VERSION}"
msg "WORK_DIR=${WORK_DIR}"
msg "LOGS_DIR=${LOGS_DIR}"
msg "VENV_NAME=${VENV_NAME}"
msg "VENV_PATH=${VENV_PATH}"
msg "ES_USERNAME=${ES_USERNAME}"
msg "ES_PASSWORD=XXXXXX"
msg "ES_PORT=${ES_PORT}"
msg "ES_URL=${ES_URL}"
msg "AMQP_PORT=${AMQP_PORT}"
msg "AMQP_IHM_PORT=${AMQP_IHM_PORT}"
msg "AMQP_URL=${AMQP_URL}"
msg "AMQP_USERNAME=${AMQP_USERNAME}"
msg "AMQP_PASSWORD=XXXXXX"
msg "GRF_PORT=${GRF_PORT}"
msg "HEALTHCHECK_HOSTNAME=${HEALTHCHECK_HOSTNAME}"
msg "INITDB_HEALTH_PORT=${INITDB_HEALTH_PORT}"
msg "ENGINE_HEALTH_PORT=${ENGINE_HEALTH_PORT}"
msg "COLLECTOR_HEALTH_PORT=${COLLECTOR_HEALTH_PORT}"

