{
 "title": "Anomaly correlation follow-up",
 "tags": [ "Anomalies_" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "dt_threshold", "label": "dt_threshold", "query": "92" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features the Anomaly correlation follow-up\n\nThe information displayed was originally taken from Ticket at JIRA ESA CAMS  \n\nInformation is available for the following missions: S1, S2, S3 and S5\n\nInformation is displayed through the following panels:\n\n- Number of observation issue linked to an anomaly\n\nTime reference for this dashboard is : observation_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "S1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% with linked anomaly ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND cams_tickets: * ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "AllDatatake",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      },
      {
       "alias": "DatatakeWithAnomaly",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Anomaly without CAMS Ticket",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND NOT cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Note: Only for Timeliness NOMINAL",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% with linked anomaly ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: * AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "AllDatatake",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      },
      {
       "alias": "DatatakeWithAnomaly",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: * AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: * AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Anomaly without CAMS Ticket",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND NOT cams_tickets: * AND timeliness: NOMINAL ",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "1000" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "last_attached_ticket : *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        },
        {
         "field": "with_anom",
         "id": "8",
         "settings": {
          "min_doc_count": "1",
          "missing": "1",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "5", "type": "sum" },
        { "field": "value_adjusted", "id": "6", "type": "sum" }
       ],
       "query": "datatake_id:* AND last_attached_ticket: * ",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        },
        {
         "field": "with_anom",
         "id": "8",
         "settings": {
          "min_doc_count": "1",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "5", "type": "sum" },
        { "field": "value_adjusted", "id": "6", "type": "sum" },
        { "field": "datatake_id", "id": "7", "type": "cardinality" }
       ],
       "query": "datatake_id:* AND expected : { 0 TO * ]",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "cams_tickets : *",
       "timeField": "observation_time_start"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "cams_tickets : *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Anomaly without CAMS Ticket",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "NOT cams_tickets : *",
       "timeField": "observation_time_start"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "NOT cams_tickets : *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "last_attached_ticket:*",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        },
        {
         "field": "with_anom",
         "id": "8",
         "settings": {
          "min_doc_count": "1",
          "missing": "1",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "5", "type": "sum" },
        { "field": "value_adjusted", "id": "6", "type": "sum" }
       ],
       "query": "datatake_id:* AND last_attached_ticket: * ",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10000" },
         "type": "terms"
        },
        {
         "field": "with_anom",
         "id": "8",
         "settings": {
          "min_doc_count": "1",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "5", "type": "sum" },
        { "field": "value_adjusted", "id": "6", "type": "sum" },
        { "field": "datatake_id", "id": "7", "type": "cardinality" }
       ],
       "query": "datatake_id:*",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "cams_tickets : *",
       "timeField": "observation_time_start"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "cams_tickets : *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Anomaly without CAMS Ticket",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" },
        { "field": "expected", "id": "4", "type": "sum" }
       ],
       "query": "NOT cams_tickets : *",
       "timeField": "observation_time_start"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "NOT cams_tickets : *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  }
 ]
}