{
 "title": "CAMS issue list",
 "tags": [ "Anomalies" ],
 "time": { "from": "now/w", "to": "now/w" },
 "templating": {
  "list": [
   {
    "name": "CamsId",
    "label": "CAMS ID",
    "query": "{\"find\":\"terms\",\"field\":\"key\"}"
   },
   { "name": "filters", "label": "CAMS Filters" },
   { "name": "filter_created", "label": "CAMS Filters per Service" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "This dashboard features the list CAMS issue retrieved from JIRA.\n\nThe information displayed was originally taken from Ticket at JIRA ESA CAMS  \n\nInformation is displayed through the following panels:\n - The creation of tickets is displayed in the form of a time series with the number of tickets created for each time frame;\n - List of tickets .\n\n Note: the time range filter on the tickets updated over the period, so if the ticket was created and updated outside this period it will not be visible\n\nTime reference for this dashboard is : updated\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Issue List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Opened and Closed tickets",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "Opened tickets",
       "bucketAggs": [
        { "field": "created", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "_id:$CamsId",
       "timeField": "created"
      },
      {
       "alias": "Closed Tickets",
       "bucketAggs": [
        { "field": "updated", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "status:closed AND _id:$CamsId",
       "timeField": "updated"
      }
     ]
    },
    {
     "title": "CAMS Anomaly",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "_id:$CamsId",
       "timeField": "updated"
      }
     ]
    }
   ]
  },
  { "title": "Ticket created for SSC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"SSC Acquisition - INS PAR KSE\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 3 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"SSC Acquisition - INS PAR KSE\"",
     "timeField": "created"
    }
   ]
  },
  { "title": "Ticket created for MPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"INTA Acquisition - MPS\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 14 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"INTA Acquisition - MPS\"",
     "timeField": "created"
    }
   ]
  },
  { "title": "Ticket created for MTI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"e-Geos Acquisition - MTI\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"e-Geos Acquisition - MTI\"",
     "timeField": "created"
    }
   ]
  },
  { "title": "Ticket created for NSG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"DLR Acquisition - NSG\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"DLR Acquisition - NSG\"",
     "timeField": "created"
    }
   ]
  },
  { "title": "Ticket created for SVL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"KSAT S1-2-3 Acquisition - SGS\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 47 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"KSAT S1-2-3 Acquisition - SGS\"",
     "timeField": "created"
    }
   ]
  },
  { "title": "Ticket created for S5P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Ticket created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "created", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "entity: \"KSAT S-5p Acquisition - INU SGS\"",
     "timeField": "created"
    }
   ]
  },
  {
   "title": "CAMS Anomaly",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 58 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "entity: \"KSAT S-5p Acquisition - INU SGS\"",
     "timeField": "created"
    }
   ]
  }
 ]
}