{
 "title": "Data Collection monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "DataSource", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "Journal",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "timeField": "last_collect_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "# Hello ${__user.login},\n\nHere are some indications on this board:\n\n####  This dashboard shows the number of products collected by **ingestion time**\n\n## Journal\n\n⬅ Last collect date must not be longer than the refresh_interval of the interface or the loop interval on the collector\n \n * Last collection date shows the last date where the collector has run on the interface\n * Last production date shows the time from now of the last colleted production\n * Tick date shows a colletor is running and had reserve the slot of collection from this time\n\n## Collection details\n\n⬇ Click on group tabs to view details on the collection during the period"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "${ds}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2.4, "x": 0, "y": 14 },
   "repeat": "ds",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ingestionTime",
       "id": "2",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "ingestionTime"
    }
   ]
  },
  {
   "title": "$ds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "ds",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "ingestionTime"
    }
   ]
  },
  {
   "title": "Collect $ds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface_name",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "ingestionTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "ingestionTime"
    }
   ]
  }
 ]
}