{
 "title": "DD Completeness (Manual Parameter Selection)",
 "tags": [ "Debug" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "product_level",
    "label": "Product Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: ${mission} AND product_level:${product_level}\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: ${mission} AND satellite_unit: ${satellite} AND product_level: ${product_level} AND product_type:$product_type\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission:$mission AND satellite_unit:$satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND prip_id:*\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: ${mission} AND product_level:${product_level} AND timeliness:$timeliness AND product_type:${product_type}\"}"
   },
   { "name": "dd_service", "label": "Dissemination service", "query": "ddip,dddas" },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a comparison between product published at the following interfaces:\n - PRIP;\n - DD DHUS, DAS.\n\nDiscrepancies are displayed through the following indicators:\n - Total missing product count;\n - Missed products over time;\n - Pie chart view of product status;\n - Detailed list of missing products.\n\nInformation is available for each mission and each PRIP managed by OMCS.\n\nTips:\n - Annotations are available on time series;\n - Mission service to consider can be selected in the upper bar.\n - Dissemination service to consider can be selected in the upper bar filter named \"Dissemination service\" ddip is DD_DHUS, dddas is DD_DAS.\n\n This Dashboard use the [Copernicus Ground Segment Sentinels Data Flow Configuration V1.2](/grafana/d/MfmL_E4Vz/dataflow-configuration?orgId=1) as reference\n\n\nNote : Some product category are not disseminated to DHUS :\n\n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  { "title": "DD Completeness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Products Published by PRIP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5))",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Products Disseminated at DD",
   "type": "stat",
   "description": "Total Disseminated Products by DD and also published @PRIP",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Disseminated Products",
   "type": "stat",
   "description": "Published @PRIP but NOT @DD",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND NOT ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Percentage of Disseminated products",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Disseminated",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Not Disseminated",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND NOT ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Disseminated products over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND NOT ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Disseminated Products List",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND NOT ${dd_service}_publication_date:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Archived products details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disseminated products per product type",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        {
         "field": "mission",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND ${dd_service}_publication_date:*",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Disseminated products per product type",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        {
         "field": "mission",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND NOT ${dd_service}_publication_date:*",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "List of Disseminated Products",
     "type": "table",
     "description": "Total Disseminated Products by DD and also published @PRIP",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness AND prip_id:* AND datatake_id:$datatake_id AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5)) AND ${dd_service}_publication_date:*",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}