{
 "title": "LTA Download Quota",
 "tags": [ "Volumes and Count" ],
 "time": { "from": "now-4d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "lta",
    "label": "LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"production_service_name\", \"query\": \"production_service_type: LTA AND mission: $mission\"}"
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "{\"find\": \"terms\", \"field\": \"service_name.keyword\", \"query\":\"*\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "This dashobard provide metrics (mainly count and volume) exposed by LTA\n\nNote: For CloudFerro we are waiting for them exposing of their metrics\n\nThe information displayed was originally taken from Metrics at LTA  \n\nTime reference for this dashboard is : timestamp\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall LTA Downloaded Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded volume over time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "a",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": { "interval": "1h", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      },
      {
       "alias": "b",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": {
          "interval": "1h",
          "min_doc_count": "1",
          "offset": "1h",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Downloaded volume over time for $lta",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "repeat": "lta",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "a",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      },
      {
       "alias": "b",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": {
          "interval": "1h",
          "min_doc_count": "0",
          "offset": "1h",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "$lta LTA Downloaded Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "lta",
   "collapsed": true,
   "panels": [
    {
     "title": "Downloaded volume for $lta",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "a",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      },
      {
       "alias": "b",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": {
          "interval": "1h",
          "min_doc_count": "0",
          "offset": "1h",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Quota Usage for $lta",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "a",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": { "interval": "1d", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "production_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      },
      {
       "alias": "b",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "6",
         "settings": {
          "interval": "1d",
          "min_doc_count": "1",
          "offset": "1d",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "production_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Daily Downloaded volume for $lta",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "a",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      },
      {
       "alias": "b",
       "bucketAggs": [
        {
         "field": "timestamp",
         "id": "7",
         "settings": {
          "interval": "1d",
          "min_doc_count": "0",
          "offset": "1d",
          "timeZone": "utc",
          "trimEdges": "0"
         },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "sum" }
       ],
       "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Downloaded volume for service $service_name ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "service_name"
  },
  {
   "title": "Downloaded volume for $service_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "a",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "alias": "b",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": {
        "interval": "1h",
        "min_doc_count": "0",
        "offset": "1h",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Quota Usage for $service_name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "a",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "alias": "b",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": {
        "interval": "1d",
        "min_doc_count": "0",
        "offset": "1d",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "daily_download_quota", "id": "1", "type": "sum" }
     ],
     "query": "service_name:$service_name",
     "timeField": "ingestionTime"
    }
   ]
  },
  {
   "title": "Downloaded volume for $service_name",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "a",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "alias": "b",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": {
        "interval": "1d",
        "min_doc_count": "0",
        "offset": "1d",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "daily_download_quota", "id": "1", "type": "sum" }
     ],
     "query": "service_name:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Downloaded volume for $service_name",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "a",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "alias": "b",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "6",
       "settings": {
        "interval": "1d",
        "min_doc_count": "0",
        "offset": "1d",
        "timeZone": "utc",
        "trimEdges": "0"
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "sum" }
     ],
     "query": "satellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_name: download AND\nservice_name: $service_name\nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "daily_download_quota", "id": "1", "type": "sum" }
     ],
     "query": "service_name:$service_name",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}