{
 "title": "System Technical Budget Thresholds",
 "tags": [ "System Technical budget" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "version", "label": "Version", "query": { "query": "" } },
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite_unit",
    "label": "Satellite Unit",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\", \"query\":\"mission: $mission\"}"
   },
   { "name": "stb_level", "label": "STB Level", "query": { "query": "" } },
   { "name": "stb_timeliness", "label": "STB Timeliness", "query": { "query": "" } },
   {
    "name": "lta_provider",
    "label": "LTA",
    "query": "{\"find\":\"terms\",\"field\":\"service_id\", \"query\":\"mission: $mission AND service_type:LTA\"}"
   },
   {
    "name": "global_threshold_volume_produced",
    "query": { "query": "" }
   },
   {
    "name": "global_threshold_volume_archived",
    "query": { "query": "" }
   },
   {
    "name": "global_threshold_volume_disseminated",
    "query": { "query": "" }
   },
   {
    "name": "global_threshold_count_produced",
    "query": { "query": "" }
   },
   {
    "name": "global_threshold_count_archived",
    "query": { "query": "" }
   },
   {
    "name": "global_threshold_count_disseminated",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_volume_disseminated",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_volume_produced",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_volume_archived",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_count_disseminated",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_count_produced",
    "query": { "query": "" }
   },
   {
    "name": "specific_threshold_count_archived",
    "query": { "query": "" }
   },
   { "name": "database_type", "query": { "query": "" } },
   { "name": "database_timeliness", "query": { "query": "" } },
   { "name": "global_type_produced", "query": { "query": "" } },
   { "name": "global_type_archived", "query": { "query": "" } },
   { "name": "global_type_disseminated", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Description",
     "type": "text",
     "gridPos": { "h": 30, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Summary ##\nThis dashboard features a comparison between the real amount of element and volumes in the database in regards with the budgeted values given in the technical budget thanks to red thresholds displayed on graphs.\n\nThe dashboard is split in 2 rows:\n- The first row gives a global overview per service type : ```Production, Archiving and Dissemination``` per satellite. In green, the volume/count in our database and in red the budgeted value. The satelite and mission can be chosen\n\n- The second row gives a more detailled view where user can also choose a specific technocal budget level and timeliness for a giner granularity\n \n\n## Timeliness lookup table ##\n\nTo match the timeliness written in the technical budget with the one from our database, the following true table has been used\n\n    Technical budget MISSION // Technical budget Timeliness // Database timelinesses\n\n    S1    ///    NTC      ///   [\"NTC\"]\n    S1    ///    NRT:     ///   [\"NRT\",\"NRT-PT\"]\n    S1    ///    A        ///   [\"NRT-PT\",\"NTC\",\"NRT\"]\n    S1    ///    AUX      ///   [\"_\"]\n    S1    ///    _        ///   [\"_\"]\n\n\n    S2    ///    NTC      ///   [\"NOMINAL,NOT_RECORDING\"]\n    S2    ///    AUX      ///   [\"AUX\"]\n    S2    ///    _        ///   [\"_\"]\n\n\n    S3    ///    NTC      ///   [\"NT\"]\n    S3    ///    NRT      ///   [\"NR,AL\"]\n    S3    ///    STC      ///   [\"ST\"]\n    S3    ///    AUX      ///   [\"SN,NS,NN,_\"]\n\n\n    S5    ///    NTC      ///   [\"OPER,OFFL\"]\n    S5    ///    AUX      ///   [\"_\"]\n    S5    ///    NRT      ///   [\"NRTI\"]\n\n\n## Facts related to technical budget v1.8 ##\n\n- element in technical budget with level L1X are rattached to L1.  EG: L1B -> L1  etc..\n\n- the typo in technical budget  type ```OFFL_L2__HCCO_``` instead of ```OFFL_L2__HCHO_``` has been taken into account in our calculation\n\n- type ```OBS_SS__` ``` is not an AUX and has not level so it has been disregarded from our calculation\n\n- All auxiliary have their level defined to ```AUX``` even if not written in the databudget\n\n- Some types in the technical budget have a suffix which does not exist for elements in our database ```(AUX_ECE)   (EUP)   (SH/SV/DH/DV)  (SH/SV) ``` so they have been removed to match with our data\n\n- Somes element in the databudget have their field ```#Num/day``` and/or ```Volume per day [GB]``` not defined. It will lead to an incomplete threshold definition\n\n- Some element for mission S1 have their level set to A without a timeliness defined. We kept them in a separate A level and we associated it to timeliness [\"NRT-PT\",\"NTC\",\"NRT\"] as a guess\n\n## Note ## \n- It is possible to select the version of the technical budget to use by modifying the version variable\n- The granularity of the data is a day\n\n\n Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view.\",\n"
     }
    }
   ]
  },
  { "title": "Global Threshold", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Global Threshold PRIP $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_volume_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Global Threshold LTA $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_volume_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Global Dissemination LTA $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_volume_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "PRIP Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "repeat": "service_type",
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:PRIP AND product_type:$global_type_produced",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_volume_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "LTA Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:LTA AND service_id:$lta_provider AND product_type:$global_type_archived",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_volume_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Dissemination Data Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:DD AND product_type:$global_type_disseminated",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_volume_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "Global Threshold PRIP Count $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_count_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Global Threshold LTA Count $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_count_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Global Threshold Dissemination Count $satellite_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$global_threshold_count_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "PRIP Data Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:PRIP  AND product_type:$global_type_produced",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_count_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "LTA Data Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:LTA AND service_id:$lta_provider  AND product_type:$global_type_archived",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_count_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Dissemination Data Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:DD  AND product_type:$global_type_disseminated",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$global_threshold_count_disseminated",
     "type": "math"
    }
   ]
  },
  { "title": "Specific Threshold", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Volume Threshold PRIP $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_volume_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume Threshold LTA $satellite_unit level : $stb_level timeliness : $stb_timeliness provider:$lta_provider",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_volume_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume Threshold Disseminated $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_volume_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume PRIP $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:PRIP AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene} ",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_volume_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume LTA $satellite_unit level : $stb_level timeliness : $stb_timeliness provider:$lta_provider",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:LTA AND service_id:$lta_provider AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_volume_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume Disseminated $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "Volume In GB in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "content_length", "id": "1", "settings": { "script": "_value / 1000000000" }, "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:DD AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_volume_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count Threshold PRIP $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_count_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count Threshold LTA $satellite_unit level : $stb_level timeliness : $stb_timeliness provider:$lta_provider",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_count_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count Threshold Disseminated $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$specific_threshold_count_disseminated",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count PRIP $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:PRIP AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_count_produced",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count LTA $satellite_unit level : $stb_level timeliness : $stb_timeliness provider:$lta_provider",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:LTA AND service_id:$lta_provider AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_count_archived",
     "type": "math"
    }
   ]
  },
  {
   "title": "Count Disseminated $satellite_unit level : $stb_level timeliness : $stb_timeliness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of document in database",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_unit:$satellite_unit AND service_type:DD AND product_type:${database_type:lucene} AND timeliness:${database_timeliness:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "expression": "$specific_threshold_count_disseminated",
     "type": "math"
    }
   ]
  }
 ]
}