{
 "title": "Consolidation Deltas",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "templating": {
  "list": [
   {
    "name": "prip_interface_name",
    "label": "PRIP Interface Name",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\"}"
   },
   {
    "name": "lta_interface_name",
    "label": "LTA Interface Name",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\"}"
   },
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "dd_interface_name",
    "label": "DD Interface Name",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\"}"
   },
   {
    "name": "auxip_interface_name",
    "label": "AUXIP Interface Name",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\"}"
   },
   {
    "name": "service_type",
    "label": "Service Type",
    "query": "{\"find\": \"terms\", \"field\": \"service_type\"}"
   },
   {
    "name": "service_id",
    "label": "Service Id",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "RAW DATA count by publication_date and service_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PRIP / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "publication_date"
    }
   ]
  },
  {
   "title": "LTA / $__interval",
   "type": "timeseries",
   "description": "$__interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "publication_date"
    },
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "creation_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "creation_date"
    }
   ]
  },
  {
   "title": "Publication Consolidation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing Publication Consolidation / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      { "expression": "$S - ($P + $E)", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Product Consolidation PRIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing PRIP Products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "prip_id:* AND prip_service: ${prip_interface_name}",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: PRIP AND NOT service_id: *Legacy AND service_id: $service_id",
       "timeField": "sensing_start_date"
      },
      { "expression": "$A - $B", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Product Consolidation LTAs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing LTA Exprivia S1 products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_Exprivia_S1_is_published: true",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: Exprivia AND mission: S1",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA Exprivia S2 products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_Exprivia_S2_is_published: true",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: Exprivia AND mission: S2",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA Exprivia S3 products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_Exprivia_S3_is_published: true",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: Exprivia AND mission: S3",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA Werum products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_Werum_is_published: true AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: Werum AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA Acri products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_Acri_is_published: true AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: Acri AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA CloudFerro products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "LTA_CloudFerro_is_published: true AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: LTA AND service_id: CloudFerro AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Product Consolidation DD/AUXIP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing DD (S2) products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "ddip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "4", "type": "count" }
       ],
       "query": "ddip_id: * AND mission: S2",
       "timeField": "ddip_publication_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "4", "type": "count" }
       ],
       "query": "service_type: DD AND mission: S2",
       "timeField": "publication_date"
      },
      { "expression": "$B - ($A/2)", "type": "math" }
     ]
    },
    {
     "title": "Missing DD (not S2)  products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "ddip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "4", "type": "count" }
       ],
       "query": "ddip_name: * AND NOT mission: S2 AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "4", "type": "count" }
       ],
       "query": "service_type: DD AND NOT mission: S2 AND mission: $mission",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing AUXIP products (by $__interval)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "alias": "Product",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "auxip_id: *",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Publications",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "service_type: AUXIP",
       "timeField": "sensing_start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Publication Consolidation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missing PRIP Publication Consolidation / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "alias": "consolidated",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "service_type: PRIP",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "raw-prip",
       "bucketAggs": [
        { "field": "start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing LTA Publication Consolidation / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "consolidated",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "service_type: LTA",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "raw-lta",
       "bucketAggs": [
        { "field": "start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing AUXIP Publication Consolidation / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "consolidated",
       "bucketAggs": [
        { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "service_type: AUXIP",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "raw-auxip",
       "bucketAggs": [
        { "field": "publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    },
    {
     "title": "Missing DD Publication Consolidation / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "consolidated",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "service_type: DD",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "raw-dd",
       "bucketAggs": [
        { "field": "start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "start_date"
      },
      { "expression": "$B - $A", "type": "math" }
     ]
    }
   ]
  },
  {
   "title": "Publication Consolidation Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missng publication updates in PRIP product",
     "type": "table",
     "description": "!!! Zoom in timeline to have below 10000 products ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "NOT product_name: *OLQC_report.tar",
       "timeField": "start_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "service_type: PRIP",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Missng publication updates in LTA product",
     "type": "table",
     "description": "!!! Zoom in timeline to have below 10000 products ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "timeField": "start_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "service_type: LTA",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Missng publication updates in DD product",
     "type": "table",
     "description": "!!! Zoom in timeline to have below 10000 products ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "timeField": "start_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "service_type: DD",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Missng publication updates in AUXIP product",
     "type": "table",
     "description": "!!! Zoom in timeline to have below 10000 products ",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "timeField": "start_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "service_type: AUXIP",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Product Consolidation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table check",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 26 }
     ]
    },
    {
     "title": "Missing PRIP updates in product",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 2, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "prip_id:* AND prip_service: ${prip_interface_name}",
       "timeField": "sensing_start_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "service_type: PRIP AND NOT service_id: *Legacy AND service_id: $service_id",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Table check",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 48 }
     ]
    },
    {
     "title": "Missing DD S2 updates in product",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 2, "y": 25 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "ddip_id:* AND mission: S2",
       "timeField": "ddip_publication_date"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission: S2 AND service_type: DD",
       "timeField": "publication_date"
      }
     ]
    }
   ]
  }
 ]
}