{
 "title": "Acquisition passes status ( from EDRS)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_id\", \"query\":\"mission:$mission\"}"
   },
   {
    "name": "geo_satellite_id",
    "label": "Geo Satellite ",
    "query": "{\"find\": \"terms\", \"field\": \"geo_satellite_id\", \"query\": \"satellite_id:$satellite_unit\"}"
   },
   {
    "name": "ground_station",
    "label": "Ground Station",
    "query": "{\"find\": \"terms\", \"field\": \"ground_station\", \"query\": \"satellite_id:$satellite_unit AND geo_satellite_id:$geo_satellite_id\"}"
   },
   { "name": "Filters" },
   { "name": "planned_link_session_start", "label": "Planned_link_session_start", "query": { "query": "" } },
   { "name": "planned_link_session_stop", "label": "Planned_link_session_stop", "query": { "query": "" } },
   { "name": "datatake_id", "label": "Datatake", "query": { "query": "" } },
   {
    "name": "link_session_id",
    "label": "Link_session_id",
    "query": "{\"find\": \"terms\", \"field\": \"link_session_id\", \"query\": \"satellite_id:$satellite_unit AND geo_satellite_id:$geo_satellite_id\"}"
   },
   { "name": "mission_edrs", "label": "Mission_edrs", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Acquisition passes status.\n\nInformation is available for the following missions: S1 and S2."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Acquisition passes status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Acquisition Passes Status Timeline by ground station",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Acquisition Passes Status ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "ground_station:$ground_station AND geo_satellite_id:$geo_satellite_id AND satellite_id: $satellite_unit AND mission:$mission AND link_session_id:$link_session_id",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "Planned Downlinks And Datatake Completeness Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=mission:$mission_edrs AND station:$geo_satellite_id AND effective_downlink_start:[0 TO ${planned_link_session_stop}] AND effective_downlink_stop:[${planned_link_session_start} TO *]&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "S1 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S1 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "S2 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S2 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  }
 ]
}