{
 "title": "Station Acquisition Status (X-Band)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ground_station",
    "label": "Reception Station",
    "query": "{\"find\": \"terms\", \"field\": \"ground_station\",\"query\":\"mission:$mission AND satellite_id:$satellite\"}"
   },
   {
    "name": "downlink_orbit",
    "label": "Downlink Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"downlink_orbit\",\"query\":\"mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station\"}"
   },
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\",\"query\":\"mission: *\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_id\",\"query\":\"mission: $mission\"}"
   },
   { "name": "datatake_id", "label": "Datatake_id", "query": { "query": "" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Downlink Acquisition status.\n\nInformation is taken from station reports made available through JIRA tickets.\n\nInformation is available for the following missions: S1, S2 and S3."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Station Acquisition Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Success Station Acquisition Status ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "All Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Failed Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND NOT ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Success Station Acquisition Status ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit AND ( antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK )",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Acquisition Timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Acquisitions Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Planned Downlinks And Datatake Completeness Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
     "options": {
      "content": "To view planned downlinks and associated datatake, please select downlink orbit on acquisition table."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=station:${ground_station}* AND downlink_absolute_orbit:${downlink_orbit}&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "S1 Datatake",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S1 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "S2 Datatake",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "repeat": "mission_edrs",
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:S2 AND datatake_id:${datatake_id:lucene}",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "details",
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 33 },
     "targets": [
      { "panelId": 3 }
     ]
    }
   ]
  }
 ]
}