{
 "title": "Anomaly correlation follow-up",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dt_threshold", "label": "dt_threshold", "query": "92" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features the Anomaly correlation follow-up\n\nInformation is available for the following missions: S1, S2, S3 and S5\n\nInformation is displayed through the following panels:\n\n- Number of observation issue linked to an anomaly\n\n"
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "S1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% with linked anomaly ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND cams_tickets: * ",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "AllDatatake",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      },
      {
       "alias": "DatatakeWithAnomaly",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "sensing_global_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "sensing_global_percentage", "id": "1", "type": "sum" }
       ],
       "query": "sensing_global_percentage: [0 TO dt_threshold]  AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% with linked anomaly ",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "AllDatatake",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold]",
       "timeField": "observation_time_start"
      },
      {
       "alias": "DatatakeWithAnomaly",
       "bucketAggs": [
        {
         "field": "observation_time_start",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "CAMS anomaly correlation",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "final_completeness_percentage", "id": "1", "type": "sum" }
       ],
       "query": "final_completeness_percentage: [0 TO $dt_threshold] AND cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% linked to an anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold% linked to an anomaly",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "S5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of observation completeness issue",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold%",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "stat",
     "description": "Datatake with completeness under $dt_threshold% linked to an anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Observation completeness anomaly correlation ratio",
     "type": "gauge",
     "description": "Percentage of datatake under $dt_threshold% with linked anomaly",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    },
    {
     "title": "Number of observation completeness issue linked to an anomaly",
     "type": "table",
     "description": "Datatake with completeness under $dt_threshold% linked to an anomaly",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "value_adjusted", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "datatake_id",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "timeliness",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "expected", "id": "1", "type": "sum" }
       ],
       "query": "cams_tickets: *",
       "timeField": "observation_time_start"
      }
     ]
    }
   ]
  }
 ]
}