{
 "title": "ADG Timeliness",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2, S3" },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\", \"query\":\"mission: $mission AND service_type:AUXIP\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\":\"terms\",\"field\":\"product_type\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND product_level:$product_level  AND timeliness: $timeliness AND  service_type: AUXIP\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" },
   {
    "name": "S1_30",
    "query": "AUX_WND,MPL_GTDEV,MPL_ORBPRE ,MPL_ORBRES,MPL_TLEPRE,TLM_REQ_B,TLM_REQ_D,TLM_REQ_E,TLM_REQ_F,AUX_PREORB,AUX_RESORB,AUX_POEORB"
   },
   {
    "name": "S1_10",
    "query": "AUX_ICE,AMH_ERRMAT,AMV_ERRMA,TLM_REQ_C"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a Timeliness computation of data published at the following interfaces:\n - AUXIP.\n\nAuxiliary data is divided into two categories:\n - Several per day (timeliness should be below 10 minutes);\n - One per day (timeliness should be below 30 minutes).\n\nThe list of products in the \"one per day\" category are: AUX_ICE, AMH_ERRMAT, AMV_ERRMA, TLM_REQ_C, SR_2_POL_AX, SL_2_SSTAAX and SL_2_DIMSAX.\n\nTimeliness is computed from metadata attached to each Auxiliary data (Publication Date - Origin Date).\n\nDiscrepancies are displayed through the following indicators:\n - Percent of data below timeliness threshold;\n - Average timeliness of data;\n - Time series of data displayed against the timeliness threshold;\n - Detailed list of data out of accepted range.\n\nInformation is available for each mission managed by OMCS.\n\nTips:\n - Annotations are available on time series;\n - Mission to consider can be selected in the upper bar."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "ADG Timeliness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "\"Several per day\" Timeliness (< 10 min)",
   "type": "gauge",
   "description": "Timeliness for files published several times per day ",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "10 min",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "transfer_timeliness: [0 TO 600000000] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: (\"AUX_WND\" OR \"MPL_GTDEV\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL_TLEPRE\" OR \"TLM_REQ_B\" OR \"TLM_REQ_D\" OR \"TLM_REQ_E\" OR \"TLM_REQ_F\" OR \"AUX_PREORB\" OR \"AUX_RESORB\" OR \"AUX_POEORB\" OR \"AUX_ECMWFD\" OR \"AUX_CAMSFO\" OR \"AUX_UT1UTC\" OR \"TLM__REQ_A\" OR \"TLM__REQ_B\" OR \"REP__CHF__\" OR \"REP__FCHF__\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL__GTDEV\" OR \"AX___MF1_AX\" OR \"AX___MFA_AX\" OR \"AX___MA1_AX\" OR \"AX___MF2_AX\" OR \"AX___MA2_AX\" OR \"SR___MDO_AX\" OR \"SR_2_PMPSAX\" OR \"SR_2_RMO_AX\" OR \"SR_2_PMO_AX\" OR \"AX___FPO_AX\" OR \"AX___FRO_AX\" OR \"AUX_POEORB\" OR \"AUX_GNSSRD\" OR \"MW_1_DNB_AX\" OR \"MW_1_NIR_AX\" OR \"SL_1_VSC_AX\" OR \"SR_1_CA1LAX\" OR \"SR_1_CA1SAX\" OR \"SR_1_CA2CAX\" OR \"SR_1_CA2KAX\" OR \"SR_2_NRPPAX OR SR_2_PCPPAX\" OR \"SR_2_PMPPAX\" OR \"SR___MGNPAX\" OR \"SR___POEPAX\" OR \"SR___ROE_AX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: (\"AUX_WND\" OR \"MPL_GTDEV\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL_TLEPRE\" OR \"TLM_REQ_B\" OR \"TLM_REQ_D\" OR \"TLM_REQ_E\" OR \"TLM_REQ_F\" OR \"AUX_PREORB\" OR \"AUX_RESORB\" OR \"AUX_POEORB\" OR \"AUX_ECMWFD\" OR \"AUX_CAMSFO\" OR \"AUX_UT1UTC\" OR \"TLM__REQ_A\" OR \"TLM__REQ_B\" OR \"REP__CHF__\" OR \"REP__FCHF__\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL__GTDEV\" OR \"AX___MF1_AX\" OR \"AX___MFA_AX\" OR \"AX___MA1_AX\" OR \"AX___MF2_AX\" OR \"AX___MA2_AX\" OR \"SR___MDO_AX\" OR \"SR_2_PMPSAX\" OR \"SR_2_RMO_AX\" OR \"SR_2_PMO_AX\" OR \"AX___FPO_AX\" OR \"AX___FRO_AX\" OR \"AUX_POEORB\" OR \"AUX_GNSSRD\" OR \"MW_1_DNB_AX\" OR \"MW_1_NIR_AX\" OR \"SL_1_VSC_AX\" OR \"SR_1_CA1LAX\" OR \"SR_1_CA1SAX\" OR \"SR_1_CA2CAX\" OR \"SR_1_CA2KAX\" OR \"SR_2_NRPPAX OR SR_2_PCPPAX\" OR \"SR_2_PMPPAX\" OR \"SR___MGNPAX\" OR \"SR___POEPAX\" OR \"SR___ROE_AX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"Several per day\" average timeliness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "avg" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\" OR \"AUX_WND\" OR \"MPL_GTDEV\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL_TLEPRE\" OR \"TLM_REQ_B\" OR \"TLM_REQ_D\" OR \"TLM_REQ_E\" OR \"TLM_REQ_F\" OR \"AUX_PREORB\" OR \"AUX_RESORB\" OR \"AUX_POEORB\" OR \"AUX_ECMWFD\" OR \"AUX_CAMSFO\" OR \"AUX_UT1UTC\" OR \"TLM__REQ_A\" OR \"TLM__REQ_B\" OR \"REP__CHF__\" OR \"REP__FCHF__\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL__GTDEV\" OR \"AX___MF1_AX\" OR \"AX___MFA_AX\" OR \"AX___MA1_AX\" OR \"AX___MF2_AX\" OR \"AX___MA2_AX\" OR \"SR___MDO_AX\" OR \"SR_2_PMPSAX\" OR \"SR_2_RMO_AX\" OR \"SR_2_PMO_AX\" OR \"AX___FPO_AX\" OR \"AX___FRO_AX\" OR \"AUX_POEORB\" OR \"AUX_GNSSRD\" OR \"MW_1_DNB_AX\" OR \"MW_1_NIR_AX\" OR \"SL_1_VSC_AX\" OR \"SR_1_CA1LAX\" OR \"SR_1_CA1SAX\" OR \"SR_1_CA2CAX\" OR \"SR_1_CA2KAX\" OR \"SR_2_NRPPAX OR SR_2_PCPPAX\" OR \"SR_2_PMPPAX\" OR \"SR___MGNPAX\" OR \"SR___POEPAX\" OR \"SR___ROE_AX\") AND product_type: ${product_type}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"Several per day\" timeliness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Timeliness",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "max" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\" OR \"AUX_WND\" OR \"MPL_GTDEV\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL_TLEPRE\" OR \"TLM_REQ_B\" OR \"TLM_REQ_D\" OR \"TLM_REQ_E\" OR \"TLM_REQ_F\" OR \"AUX_PREORB\" OR \"AUX_RESORB\" OR \"AUX_POEORB\" OR \"AUX_ECMWFD\" OR \"AUX_CAMSFO\" OR \"AUX_UT1UTC\" OR \"TLM__REQ_A\" OR \"TLM__REQ_B\" OR \"REP__CHF__\" OR \"REP__FCHF__\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL__GTDEV\" OR \"AX___MF1_AX\" OR \"AX___MFA_AX\" OR \"AX___MA1_AX\" OR \"AX___MF2_AX\" OR \"AX___MA2_AX\" OR \"SR___MDO_AX\" OR \"SR_2_PMPSAX\" OR \"SR_2_RMO_AX\" OR \"SR_2_PMO_AX\" OR \"AX___FPO_AX\" OR \"AX___FRO_AX\" OR \"AUX_POEORB\" OR \"AUX_GNSSRD\" OR \"MW_1_DNB_AX\" OR \"MW_1_NIR_AX\" OR \"SL_1_VSC_AX\" OR \"SR_1_CA1LAX\" OR \"SR_1_CA1SAX\" OR \"SR_1_CA2CAX\" OR \"SR_1_CA2KAX\" OR \"SR_2_NRPPAX OR SR_2_PCPPAX\" OR \"SR_2_PMPPAX\" OR \"SR___MGNPAX\" OR \"SR___POEPAX\" OR \"SR___ROE_AX\") AND product_type : ${product_type}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" timeliness (< 30 min)",
   "type": "gauge",
   "description": "Timeliness for files published once or less than once per day",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "30 min",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "transfer_timeliness: [0 TO 1800000000] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type : (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type : (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" average timeliness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "avg" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type : (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" timeliness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Timeliness",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "max" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type : (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\") AND product_type: $product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Out of timeliness product list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Out of timeliness products (several per day)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "< 3h",
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "transfer_timeliness: [600000000 TO *] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: (\"AUX_WND\" OR \"MPL_GTDEV\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL_TLEPRE\" OR \"TLM_REQ_B\" OR \"TLM_REQ_D\" OR \"TLM_REQ_E\" OR \"TLM_REQ_F\" OR \"AUX_PREORB\" OR \"AUX_RESORB\" OR \"AUX_POEORB\" OR \"AUX_ECMWFD\" OR \"AUX_CAMSFO\" OR \"AUX_UT1UTC\" OR \"TLM__REQ_A\" OR \"TLM__REQ_B\" OR \"REP__CHF__\" OR \"REP__FCHF__\" OR \"MPL_ORBPRE\" OR \"MPL_ORBRES\" OR \"MPL__GTDEV\" OR \"AX___MF1_AX\" OR \"AX___MFA_AX\" OR \"AX___MA1_AX\" OR \"AX___MF2_AX\" OR \"AX___MA2_AX\" OR \"SR___MDO_AX\" OR \"SR_2_PMPSAX\" OR \"SR_2_RMO_AX\" OR \"SR_2_PMO_AX\" OR \"AX___FPO_AX\" OR \"AX___FRO_AX\" OR \"AUX_POEORB\" OR \"AUX_GNSSRD\" OR \"MW_1_DNB_AX\" OR \"MW_1_NIR_AX\" OR \"SL_1_VSC_AX\" OR \"SR_1_CA1LAX\" OR \"SR_1_CA1SAX\" OR \"SR_1_CA2CAX\" OR \"SR_1_CA2KAX\" OR \"SR_2_NRPPAX OR SR_2_PCPPAX\" OR \"SR_2_PMPPAX\" OR \"SR___MGNPAX\" OR \"SR___POEPAX\" OR \"SR___ROE_AX\") AND product_type: $product_type",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": " Out of timeliness products (one per day)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "< 3h",
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": " transfer_timeliness: [1800000000 TO *] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type : (\"AUX_ICE\" OR \"AMH_ERRMAT\" OR \"AMV_ERRMA\" OR \"TLM_REQ_C\" OR \"SR_2_POL_AX\" OR \"SL_2_SSTAAX\" OR \"SL_2_DIMSAX\") AND product_type: $product_type",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}