{
 "title": "DD Timeliness",
 "tags": [ "Timeliness" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\", \"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\":\"terms\",\"field\":\"timeliness\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\":\"terms\",\"field\":\"product_level\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND timeliness: $timeliness\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\":\"terms\",\"field\":\"product_type\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND product_level:$product_level  AND timeliness: $timeliness\"}"
   },
   {
    "name": "lta_service",
    "label": "LTA Service",
    "query": "{\"find\":\"terms\",\"field\":\"service_id\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND service_type: LTA\"}"
   },
   {
    "name": "prip_service",
    "label": "PRIP Service",
    "query": "{\"find\":\"terms\",\"field\":\"service_id\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit AND service_type: PRIP\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a Timeliness computation of products published at the following interfaces:\n - PRIP;\n - LTA;\n - DD DHUS.\n\nTimeliness is computed from metadata attached to each product:\n - Production Time is (Publication Date - Origin Date);\n - From sensing timeliness (Publication Date - Content Date/End (which is the end of sensing)).\n\nDiscrepancies are displayed through the following indicators:\n - Minimum, maximum, average timeliness;\n - Distribution of timeliness in various time ranges.\n\nInformation is available for each mission and interface managed by OMCS.\n\nTips:\n - Mission to consider can be selected in the upper bar.\n\n Note : \n - Timeliness \"_\" selects HKTM files which are not disseminated to DD"
     }
    }
   ]
  },
  { "title": "DD : from PRIP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Min from PRIP to DD timelinesss",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_prip_ddip_timeliness", "id": "1", "settings": { "script": "_value/60000000" }, "type": "min" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type} AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Average from PRIP to DD  timelinesss",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_prip_ddip_timeliness", "id": "1", "settings": { "script": "_value / 60000000" }, "type": "sum" },
      {
       "hide": false,
       "id": "3",
       "type": "count"
      }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type} AND timeliness:${timeliness} AND from_prip_ddip_timeliness:*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Max from PRIP to DD timelinesss",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_prip_ddip_timeliness", "id": "1", "settings": { "script": "_value/60000000" }, "type": "max" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type} AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Distribution from PRIP to DD according to thresholds",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "< 1h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: [0 TO 360000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "1h - 2h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {360000000 TO 7200000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2h - 3h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {7200000000 TO 10800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "3h - 8h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {10800000000 TO 28800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "8h - 12h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {28800000000 TO 43200000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "12h - 24h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {43200000000 TO 86400000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "24h - 2d",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {86400000000 TO 172800000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2d - 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {172800000000 TO 2592000000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "> 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {2592000000000 TO *] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Value",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "< 1h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: [0 TO 360000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "1h - 2h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {360000000 TO 7200000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2h - 3h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {7200000000 TO 10800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "3h - 8h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {10800000000 TO 28800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "8h - 12h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {28800000000 TO 43200000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "12h - 24h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {43200000000 TO 86400000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "24h - 2d",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {86400000000 TO 172800000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2d - 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {172800000000 TO 2592000000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "> 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {2592000000000 TO *] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "< 1h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: [0 TO 360000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "1h - 2h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {360000000 TO 7200000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2h - 3h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {7200000000 TO 10800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "3h - 8h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {10800000000 TO 28800000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "8h - 12h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {28800000000 TO 43200000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "12h - 24h",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {43200000000 TO 86400000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "24h - 2d",
     "bucketAggs": [
      {
       "field": "prip_publication_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {86400000000 TO 172800000000 ] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "2d - 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {172800000000 TO 2592000000000] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "> 1m",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_ddip_timeliness: {2592000000000 TO *] AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_level:${product_level} AND product_type:${product_type}  AND timeliness:${timeliness}",
     "timeField": "sensing_start_date"
    }
   ]
  }
 ]
}