{
 "title": "AUXIP-LTA Completeness",
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: ${mission} AND auxip_id:*\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: ${mission} AND timeliness:$timeliness\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: ${mission} AND product_level:${product_level} AND timeliness:$timeliness AND auxip_id:*\"}"
   },
   {
    "name": "lta",
    "label": "LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\", \"query\": \"service_type: LTA\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a comparison between product published at the following interfaces:\n - AUXIP;\n - LTA.\n\nDiscrepancies are displayed through the following indicators:\n - Total missing product count;\n - Missed products over time;\n - Pie chart view of product status;\n - Detailed list of missing products.\n\nInformation is available for each mission and each LTA managed by OMCS.\n\nTips:\n - Annotations are available on time series;\n - Mission and LTA service to consider can be selected in the upper bar.\n"
     }
    }
   ]
  },
  { "title": "AUXIP-LTA Completeness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Products Published by AUXIP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_level:$product_level AND product_type:$product_type AND auxip_id: *",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Products Archived by LTA",
   "type": "stat",
   "description": "Total Archived Products by LTA and also published @AUXIP",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type:$product_type AND auxip_id: * AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Archived Products",
   "type": "stat",
   "description": "Published @AUXIP but NOT @LTA",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_level:$product_level AND product_type:$product_type AND auxip_id: * AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )\n",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Published",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND  product_level:$product_level AND product_type:$product_type AND auxip_id: *",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Percentage of Archived products LTA",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_level:$product_level AND product_type:$product_type AND auxip_id: * AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND  product_level:$product_level AND product_type:$product_type AND auxip_id: * AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Archived products over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND  product_level:$product_level AND product_type:$product_type AND auxip_id: * AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Archived Products List",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_level:$product_level AND product_type:$product_type AND auxip_id: * AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  },
  { "title": "Archived products details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Archived products per product type",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      {
       "field": "mission",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_level:$product_level AND product_type:$product_type AND auxip_id: * AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "List of Archived Products",
   "type": "table",
   "description": "Total Archived Products by LTA and also published @AUXIP",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND  product_level:$product_level AND product_type:$product_type AND auxip_id: * AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
     "timeField": "sensing_start_date"
    }
   ]
  }
 ]
}