{
 "title": "PRIP-DD Completeness",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: ${mission} \"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: ${mission} AND timeliness:$timeliness\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: ${mission} AND product_level:${product_level} AND timeliness:$timeliness\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: ${mission} AND product_level:${product_level} AND timeliness:$timeliness AND product_type:${product_type}\"}"
   },
   {
    "name": "datatake",
    "label": "Datatake",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5) ) AND prip_id: *\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a comparison between product published at the following interfaces:\n - PRIP;\n - DD DHUS.\n\nDiscrepancies are displayed through the following indicators:\n - Total missing product count;\n - Missed products over time;\n - Pie chart view of product status;\n - Detailed list of missing products.\n\nInformation is available for each mission and each PRIP managed by OMCS.\n\nTips:\n - Annotations are available on time series;\n - Mission service to consider can be selected in the upper bar."
     }
    }
   ]
  },
  { "title": "PRIP-DD Completeness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Products Published by PRIP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Products Disseminated at DHUS",
   "type": "stat",
   "description": "Total Archived Products by LTA and also published @AUXIP",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND timeliness : $timeliness AND product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND ddip_name:*) OR (mission:S2  AND ddip_id:* AND instrument_mode:$instrument_mode) OR (mission:S3 AND ddip_name:*) OR (mission:S5 AND ddip_name:*) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Disseminated Products",
   "type": "stat",
   "description": "Published @AUXIP but NOT @LTA",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND ddip_name:*) OR (mission:S2 AND instrument_mode:$instrument_mode AND ddip_id:*) OR (mission:S3 AND ddip_name:*) OR (mission:S5 AND ddip_name:*) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Published",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode) OR (mission:S2 AND instrument_mode:$instrument_mode) OR (mission:S3) OR (mission:S5) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Percentage of Disseminated products",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND ddip_name: *) OR (mission:S2 AND instrument_mode:$instrument_mode AND ddip_id: *) OR (mission:S3 AND ddip_name: *) OR (mission:S5 AND ddip_name: *) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND NOT ddip_name: *) OR (mission:S2 AND instrument_mode:$instrument_mode AND NOT ddip_id: *) OR (mission:S3 AND NOT ddip_name: *) OR (mission:S5 AND NOT ddip_name: *) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Archived products over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Not Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND NOT ddip_name:*) OR (mission:S2 AND instrument_mode:$instrument_mode AND NOT ddip_id:*) OR (mission:S3 AND NOT ddip_name:*) OR (mission:S5 AND NOT ddip_name:*) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Not Disseminated Products List",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND NOT ddip_name: *) OR (mission:S2 AND instrument_mode:$instrument_mode AND NOT ddip_id: *) OR (mission:S3 AND NOT ddip_name: *) OR (mission:S5 AND NOT ddip_name: *) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  { "title": "Archived products details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Archived products per product type",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      {
       "field": "mission",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND ddip_name: *) OR (mission:S2 AND instrument_mode:$instrument_mode AND ddip_id: *) OR (mission:S3 AND ddip_name: *) OR (mission:S5 AND ddip_name: *) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "List of Archived Products",
   "type": "table",
   "description": "Total Archived Products by LTA and also published @AUXIP",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness product_level:$product_level AND product_type:$product_type AND ((mission:S1 AND instrument_mode:$instrument_mode AND ddip_name: *) OR (mission:S2 AND instrument_mode:$instrument_mode AND ddip_id: *) OR (mission:S3 AND ddip_name: *) OR (mission:S5 AND ddip_name: *) ) AND prip_id: * AND datatake_id:$datatake",
     "timeField": "sensing_start_date"
    }
   ]
  }
 ]
}