{
 "title": "S1 Datatake Completeness (Produced vs Planned)",
 "description": "This dashboard show statistics about S1 datatake production completeness (produced vs planned)",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode AND datatake_id:$datatake_id\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND instrument_mode:$instrument_mode AND datatake_id:$datatake_id AND product_level:$product_level\"}"
   },
   {
    "name": "absolute_orbit",
    "label": "Absolute Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"absolute_orbit\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument Mode",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode \"}"
   },
   { "name": "station", "label": "Station", "query": { "query": "" } },
   { "name": "downlink_orbit", "label": "Downlink orbit", "query": { "query": "" } },
   { "name": "Filter", "label": "Ad-Hoc filter" },
   { "name": "effective_downlink_start", "label": "Effective_downlink_start", "query": { "query": "" } },
   { "name": "effective_downlink_stop", "label": "Effective_downlink_stop", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard features Completeness computation on a single datatake of S1 mission.\r\n\r\nComparison is done between the following:\r\n - Mission Planning (MP): Planned products;\r\n - PRIP: Produced products.\r\n\r\nL1_SLC and L2_OCN expected products are determined with intersection of footprints taken from RAW_0S.\r\n\r\nL0 products expected duration are based on L0 sensing duration taken from MP.\r\nL1/L2 products expected duration are based on Observation Duration taken from MP (except for RF_RAW__0S products that have an expected duration of 2.8s).\r\n\r\nTips:\r\n - Best approach is to start in Production Completeness dashboard and select one datatake to explore from there;\r\n - Satellite to consider can be selected in the upper bar."
   }
  },
  {
   "title": "Datatake Completeness Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datatake overall information & Completeness",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake anomalies",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND cams_tickets: * ",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Expected Tiles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Expected OCN",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "datatake_id:$datatake_id AND product_type:${instrument_mode}RAW__0S AND OCN_coverage_percentage: {20 TO *]",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Expected SLC",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "datatake_id:$datatake_id AND product_type:${instrument_mode}RAW__0S AND SLC_coverage_percentage: {0 TO *]",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "per Product Level Completeness",
   "type": "table",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Produced Tiles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "OCN Tiles",
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "datatake_id:$datatake_id AND product_type:${instrument_mode}OCN__2*",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "SLC Tiles",
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "datatake_id:$datatake_id AND product_type:${instrument_mode}SLC__1*",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "per Product type completeness",
   "type": "table",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake & Products Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datatake Timeline and Overall Completeness",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake Products Timeline (grouped by product type)",
   "type": "marcusolsson-gantt-panel",
   "description": "This timeline shows in green the produced products grouped per product type. Red bars shows L0 production gaps.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:* AND product_level:$product_level AND product_type:$product_type",
     "timeField": "sensing_start_date"
    },
    {
     "root_selector": "_source.missing_periods",
     "source": "url",
     "type": "json",
     "url": "/cds-datatake/_doc/${satellite}-${datatake_id}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "List of L0 production gaps",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND missing_periods: *",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake product list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datatake Products published at PRIP",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:* AND product_level:$product_level AND product_type:$product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Datatake Products Timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:*  AND product_level:$product_level AND product_type:$product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  { "title": "Downlinks information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Planned downlinks",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-downlink-datatake/_search?q=datatake_id:${datatake_id}%20AND%20satellite_unit:${satellite}&size=1000",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Acquisition status x-Band",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "global_query_id": "raw-data-aps-product",
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-acquisition-pass-status/_search?q=satellite_id:${satellite}%20AND%20downlink_orbit:${downlink_orbit}%20AND ground_station:${station:lucene}&size=1000",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Acquisition status EDRS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "root_selector": "hits.hits",
     "source": "url",
     "type": "json",
     "url": "/cds-edrs-acquisition-pass-status-product/_search?q=satellite_id:${satellite}%20AND%20geo_satellite_id:${station:lucene}%20AND%20planned_link_session_start:[0 TO ${effective_downlink_start}]%20AND%20planned_link_session_stop:[${effective_downlink_stop} TO *]",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}