{
 "title": "S2 Datatake Completeness (Produced vs Planned)",
 "description": "This dashboard show statistics about S2 datatake production completeness (produced vs planned)",
 "time": { "from": "2022-05-04T23:55:40.464Z", "to": "2022-05-05T00:02:05.184Z" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S2" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode AND datatake_id:$datatake_id\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode AND datatake_id:$datatake_id AND product_level:$product_level\"}"
   },
   {
    "name": "absolute_orbit",
    "label": "Absolute Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"absolute_orbit\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument Mode",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode \"}"
   },
   { "name": "downlink_orbit", "label": "Downlink orbit", "query": { "query": "" } },
   { "name": "station", "label": "Station", "query": { "query": "" } },
   { "name": "effective_downlink_start", "label": "Effective_downlink_start", "query": { "query": "" } },
   { "name": "effective_downlink_stop", "label": "Effective_downlink_stop", "query": { "query": "" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Completeness computation on a single datatake of S2 mission.\r\n\r\nComparison is done between the following:\r\n - Mission Planning (MP): Planned products;\r\n - PRIP: Produced products.\r\n\r\nTL / TC expected products are determined by intersection of footprints taken from MSI_L1C_DS.\r\n\r\nExpected Granules (MSI_L0__GR) are based on the number of scene of the level multiplied per 12. (TODO: use MSI_??_DS).\r\n\r\nL0_DS products expected duration are based on Observation Duration taken from MP.\r\nL1B_DS, L1C_DS and L2A products expected duration are based on Observation Duration of MP minus 2*3,608s (duration of one scene).\r\n\r\nFinally, if scene count is inferior to 3, L0 products are the only ones expected.\r\n\r\nTips:\r\n - Best approach is to start in Production Completeness dashboard and select one datatake to explore from there;\r\n - Satellite to consider can be selected in the upper bar."
     }
    }
   ]
  },
  { "title": "Datatake Completeness Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Datatake overall information & Completeness",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake anomalies",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND cams_tickets: *",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Level Completeness",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product type completeness",
   "type": "table",
   "description": "Be aware that TL TC values depends on recieved DS,  that means that we could have 100% of completeness for TL TC and DS 25% so TL TC are 100% complete for recieved DS but only 25% of expected DS.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  { "title": "Datatake & Products Timelines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Datatake Timeline and Overall Completeness",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake Products Timeline (grouped by product type)",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:*  AND product_level:$product_level AND product_type:$product_type",
     "timeField": "sensing_start_date"
    },
    {
     "json_options": {
      "root_is_not_array": false
     },
     "parser": "simple",
     "root_selector": "_source.missing_periods",
     "source": "url",
     "type": "json",
     "url": "/cds-datatake/_doc/${satellite}-${datatake_id}",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Missing Periods",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND missing_periods: *",
     "timeField": "observation_time_start"
    }
   ]
  },
  { "title": "Datatake product list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Datatake Products published at PRIP",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:*  AND product_level:$product_level AND product_type:$product_type",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Downlinks information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Planned downlinks",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-downlink-datatake/_search?q=datatake_id:${datatake_id}%20AND%20satellite_unit:${satellite}&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Acquisition status x-Band",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "global_query_id": "raw-data-aps-product",
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-acquisition-pass-status/_search?q=satellite_id:${satellite}%20AND%20downlink_orbit:${downlink_orbit:lucene}%20AND ground_station:${station:lucene}&size=1000",
       "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Acquisition status EDRS",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "global_query_id": "raw-data-aps-edrs-product",
       "root_selector": "hits.hits",
       "source": "url",
       "type": "json",
       "url": "/cds-edrs-acquisition-pass-status/_search?q=satellite_id:${satellite}%20AND%20geo_satellite_id:${station:lucene}%20AND%20planned_link_session_start:[0 TO ${effective_downlink_start}]%20AND%20planned_link_session_stop:[${effective_downlink_stop} TO *]",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  }
 ]
}