{
 "title": "LTA Usage",
 "tags": [ "Volumes and Count" ],
 "time": { "from": "now-4d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\": \"terms\", \"field\": \"mission\"}"
   },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "lta",
    "label": "LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"production_service_name\", \"query\": \"production_service_type: LTA AND mission: $mission\"}"
   },
   {
    "name": "product_type",
    "label": "Product type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\", \"query\":\"mission: ${mission} AND satellite_unit: ${satellite}\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashobard provide metrics (mainly count and volume) exposed by LTA\n\nNote: For CloudFerro we are waiting for them exposing of their metrics\n\nThe information displayed was originally taken from Metrics at LTA  \n\nTime reference for this dashboard is : timestamp\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall LTA usage - Product Volume & Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Volume $lta",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "satellite_unit",
       "id": "7",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "8",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "production_service_name",
       "id": "9",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "metric_sub_type.keyword",
       "id": "11",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "counter", "id": "1", "type": "max" }
     ],
     "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product volume over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "mission",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "counter",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product count over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "mission",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "counter",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_sub_type : \"count\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product volume over time for $lta",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "repeat": "lta",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "mission",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "counter",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_sub_type : \"size\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Product count over time for $lta",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "repeat": "lta",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "production_service_name",
       "id": "11",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "mission",
       "id": "12",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "satellite_unit",
       "id": "13",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "product_type",
       "id": "14",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "counter",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_sub_type : \"count\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "$lta LTA usage - Product Volume & Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "lta",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume $lta",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "satellite_unit",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "mission",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "metric_sub_type.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "max" }
       ],
       "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "$lta LTA product volume over time ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "mission",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "satellite_unit",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "timestamp",
         "id": "8",
         "settings": { "interval": "1d", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "field": "counter", "id": "1", "type": "max" }
       ],
       "query": "product_type : $product_type AND\nsatellite_unit : $satellite AND \nmission: $mission AND \nproduction_service_name: $lta AND \nmetric_sub_type : \"size\"",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}