{
 "title": "LTA Completeness",
 "tags": [ "Completeness" ],
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   { "name": "level", "label": "Level", "query": { "query": "" } },
   {
    "name": "product_type",
    "label": "Product type",
    "query": {
     "query": "{\"find\": \"terms\", \"field\": \"product_type\"}"
    }
   },
   {
    "name": "lta",
    "label": "LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\", \"query\": \"service_type: LTA  AND mission: $mission\"}"
   },
   {
    "name": "all_lta",
    "label": "ALL LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\", \"query\": \"service_type: LTA  AND mission: $mission\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a comparison between product published at the following interfaces:\n - AUXIP;\n - LTA.\n\nDiscrepancies are displayed through the following indicators:\n - Total missing product count;\n - Missed products over time;\n - Pie chart view of product status;\n - Detailed list of missing products.\n\nInformation is available for each mission and each LTA managed by OMCS.\n\nFor S5P Satellite, L1 & L2 products are only archived to DLR and not to CloudFerro LTA\n\nTips:\n - Annotations are available on time series;\n - Mission and LTA service to consider can be selected in the upper bar.\n\nThis Dashboard use the [Copernicus Ground Segment Sentinels Data Flow Configuration V1.2](/grafana/d/MfmL_E4Vz/dataflow-configuration?orgId=1) as reference\n\nThe information displayed was originally taken from Product at PRIP LTA  \n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  {
   "title": "LTA Completeness Overview (Not archived products)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "$all_lta",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "repeat": "all_lta",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${all_lta}_is_published: true OR LTA_${all_lta}_S1_is_published: true OR LTA_${all_lta}_S2_is_published: true OR LTA_${all_lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Published",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: $mission AND satellite_unit : $satellite AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Detailed LTA Completeness ($lta)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "lta",
   "collapsed": true,
   "panels": [
    {
     "title": "Products Published by AUXIP and PRIP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Products Archived by LTA",
     "type": "stat",
     "description": "Total Archived Products by LTA and also published @AUXIP",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived Products",
     "type": "stat",
     "description": "Published @AUXIP but NOT @LTA",
     "gridPos": { "h": 4, "w": 5, "x": 11, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Published",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Percentage of Archived products LTA",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Not Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type:$product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived products over time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "Not Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived Products List",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Archived products per product type",
     "type": "barchart",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        {
         "field": "mission",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )\nAND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "List of Archived Products",
     "type": "table",
     "description": "Total Archived Products by LTA and also published @AUXIP",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )\nAND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}