{
 "title": "S1 Production Completeness (Produced vs Planned)",
 "tags": [ "Completeness" ],
 "time": { "from": "now-8d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "absolute_orbit",
    "label": "Absolute Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"absolute_orbit\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument Mode",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND instrument_mode:$instrument_mode\"}"
   },
   {
    "name": "cams_id",
    "label": "CAMS",
    "query": "{\"find\": \"terms\", \"field\": \"cams_tickets\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode \"}"
   },
   { "name": "product_type_HK_GP", "label": "Product Type HK / GP", "query": "HK, GP" },
   { "name": "Filters", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "This dashboard features Completeness computation on S1 mission.\r\n\r\nComparison is done between the following:\r\n - Mission Planning (MP): Planned products;\r\n - PRIP: Produced products.\r\n\r\nL1_SLC and L2_OCN expected products are determined with intersection of footprints taken from RAW_0S.\r\n\r\nL0 products expected duration are based on L0 sensing duration taken from MP.\r\nL1/L2 products expected duration are based on Observation Duration taken from MP (except for RF_RAW__0S products that have an expected duration of 2.8s).\r\n\r\nTips:\r\n - Annotations are available on time series;\r\n - Satellite to consider can be selected in the upper bar.\n\nThe information displayed was originally taken from Product at PRIP and MP ACQ at AUXIP  \n\nTime reference for this dashboard is : observation_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  {
   "title": "Overall Completeness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Completeness",
   "type": "gauge",
   "description": "Overall Completeness over the period",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sensing_global_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sensing_global_value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Timeliness",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timeliness",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "sensing_global_expected", "id": "1", "type": "sum" },
      {
       "field": "sensing_global_value_adjusted",
       "hide": false,
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Level",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Average Completeness over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "sensing_global_value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "sensing_global_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit : $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake completeness timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake list",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: ${cams_id:raw} )",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake list -21d For ETA Completeness",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id AND (cams_tickets: $cams_id)",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "HKTM & GPS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HKTM Overall Completeness",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "cadip_expected",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cadip_completeness:*",
       "timeField": "execution_time"
      },
      {
       "alias": "cadip_real",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cadip_completeness: 1",
       "timeField": "execution_time"
      },
      {
       "alias": "edrs_expected",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "edrs_completeness : *",
       "timeField": "execution_time"
      },
      {
       "alias": "edrs_real",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "edrs_completeness: 1",
       "timeField": "execution_time"
      }
     ]
    },
    {
     "title": "Per acquisition type",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 3, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "cadip_expected",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cadip_completeness:*",
       "timeField": "execution_time"
      },
      {
       "alias": "cadip_real",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "cadip_completeness: 1",
       "timeField": "execution_time"
      },
      {
       "alias": "edrs_expected",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "edrs_completeness : *",
       "timeField": "execution_time"
      },
      {
       "alias": "edrs_real",
       "bucketAggs": [
        { "field": "execution_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "edrs_completeness: 1",
       "timeField": "execution_time"
      }
     ]
    },
    {
     "title": "HKTM Completeness",
     "type": "table",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "cadip_expected",
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "timeField": "execution_time"
      }
     ]
    },
    {
     "title": "HKTM & GPS Products Timeline",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND ( product_type:HK_RAW__0_ OR product_type:GP_RAW__0_) AND product_type: ${product_type_HK_GP:pipe}*",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "HKTM & GPS Products list",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND ( product_type:HK_RAW__0_ OR product_type:GP_RAW__0_) AND product_type: ${product_type_HK_GP:pipe}*",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}