{
 "title": "S2 Production Completeness (Produced vs Planned)",
 "tags": [ "Completeness" ],
 "time": { "from": "now-8d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S2" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND instrument_mode:$instrument_mode\"}"
   },
   {
    "name": "absolute_orbit",
    "label": "Absolute Orbit",
    "query": "{\"find\": \"terms\", \"field\": \"absolute_orbit\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "instrument_mode",
    "label": "Instrument Mode",
    "query": "{\"find\": \"terms\", \"field\": \"instrument_mode\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND absolute_orbit:$absolute_orbit AND timeliness:$timeliness AND instrument_mode:$instrument_mode \"}"
   },
   { "name": "Filters", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Completeness computation on S2 mission.\r\n\r\nComparison is done between the following:\r\n - Mission Planning (MP): Planned products;\r\n - PRIP: Produced products.\r\n\r\nTL / TC expected products are determined by intersection of footprints taken from MSI_L1C_DS.\r\n\r\nExpected Granules (MSI_L0__GR) are based on the number of scene of the level multiplied per 12. (TODO: use MSI_??_DS).\r\n\r\nL0_DS products expected duration are based on Observation Duration taken from MP.\r\nL1B_DS, L1C_DS and L2A products expected duration are based on Observation Duration of MP minus 2*3,608s (duration of one scene).\r\n\r\nFinally, if scene count is inferior to 3, L0 products are the only ones expected.\r\n\r\nTips:\r\n - Annotations are available on time series;\r\n - Satellite to consider can be selected in the upper bar.\n\nThe information displayed was originally taken from Product at PRIP and MP ACQ at AUXIP  \n\nTime reference for this dashboard is : observation_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  {
   "title": "Overall Completeness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Completeness",
   "type": "gauge",
   "description": "Overall Completeness over the period",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "final_completeness_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "final_completeness_value", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Timeliness",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timeliness",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "final_completeness_expected", "id": "1", "type": "sum" },
      {
       "field": "final_completeness_value",
       "hide": false,
       "id": "3",
       "type": "sum"
      }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Level",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Average Completeness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "observation_time_start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "final_completeness_value", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      {
       "field": "observation_time_start",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "final_completeness_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit : $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake completeness timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake list",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND instrument_mode : $instrument_mode AND absolute_orbit : $absolute_orbit AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "HKTM & GPS ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HKTM Production Completeness",
     "type": "gauge",
     "description": "HKTM Production Completeness over the period",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "expected",
       "bucketAggs": [
        { "field": "effective_downlink_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "completeness: *",
       "timeField": "effective_downlink_start"
      },
      {
       "alias": "real",
       "bucketAggs": [
        { "field": "effective_downlink_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "completeness: 1",
       "timeField": "effective_downlink_start"
      }
     ]
    },
    {
     "title": "HKTM & GPS Products Timeline",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 27 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND ( product_type: PRD_HKTM__ OR product_type:PRD_GP__ OR product_type:AUX_SADATA)",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "HKTM & GPS Products list",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND (product_type: PRD_HKTM__ OR product_type:PRD_GP__ OR product_type:AUX_SADATA)",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}