{
 "title": "S3 Datatake Completeness (Produced vs Planned)",
 "description": "This dashboard show statistics about S3 datatake production completeness (produced vs planned)",
 "tags": [ "Completeness" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S3" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND timeliness:$timeliness AND datatake_id:$datatake_id\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: $mission AND satellite_unit : $satellite AND datatake_id:$datatake_id AND product_level:$product_level\"}"
   },
   {
    "name": "datatake_id",
    "label": "Datatake Id",
    "query": "{\"find\": \"terms\", \"field\": \"datatake_id\",\"query\":\"mission: $mission AND satellite_unit : $satellite  AND timeliness:$timeliness \"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Completeness computation on a single datatake of S3 mission.\r\n\r\nComparison is done using the following:\r\n - PRIP: Produced products.\r\n\r\nDatatake ID are built from:\r\n - Satellite number;\r\n - Cycle number;\r\n - Relative orbit number.\r\n\r\nWhen one PRIP product is published, every expected product related to this datatake is created.\r\n\r\nMissing products are displayed in purple.\r\n\r\nTips:\r\n - Best approach is to start in Production Completeness dashboard and select one datatake to explore from there;\r\n - Satellite to consider can be selected in the upper bar (has to be the same as the datatake ID prefix).\r\n\r\nNote: \r\n - SRAL L2, VG1 and V10 products are not included in the completeness computation since these products are not systematically produced at each orbit (production is not predictable).\r\n\n\nThe information displayed was originally taken from Product at PRIP  \n\nTime reference for this dashboard is : observation_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Datatake Completeness Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datatake Completeness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "datatake_id",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value_adjusted", "id": "1", "type": "sum" },
      { "field": "expected", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Level Completeness",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "product_level",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" },
      { "field": "value_adjusted", "id": "3", "type": "sum" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake anomalies",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness AND datatake_id : $datatake_id AND cams_tickets: * ",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "per Product Type Completeness $product_level",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "product_level",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_level : $product_level",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake Completeness per Product Type & Category",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_unit: $satellite AND timeliness : $timeliness  AND datatake_id : $datatake_id AND product_type : $product_type ",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "Datatake & Products Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Datatake Products Timeline (grouped by product type)",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:* AND product_level:$product_level AND product_type:$product_type",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  {
   "title": "Datatake product list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Datatake Products published at PRIP",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:* AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Datatake Products Timeline",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission:$mission AND satellite_unit: $satellite AND datatake_id : $datatake_id AND prip_publication_date:*  AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}