{
 "title": "Home",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "version", "query": "%version%" },
   { "name": "deploymentDate", "query": "2024-06-14" },
   {
    "name": "selected_tag",
    "query": "Acquisition,Timeliness,Volume and Count,Completeness,System Technical budget,Unavailability,Anomalies,Monitoring"
   },
   { "name": "product_type_lta", "query": { "query": "" } },
   { "name": "product_level_lta", "label": "Product Level", "query": { "query": "" } },
   { "name": "product_level_dd", "query": { "query": "" } },
   { "name": "product_type_dd", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"position:relative;font-size:30px;color:#e8e8e4;background-color:#003247;width:100%;height:100px;text-align:center;padding-top:20px\">\r\n   Welcome to OMCS Operational Dashboard\r\n   <div>\r\n   <div style=\"position:absolute;text-align:right;font-size:12px;padding-right:15px;font-size:12px\">\r\n      Release Date: ${deploymentDate} | v${version}\r\n   </div>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:18px\">Archiving Completeness</center></p> \r\n\r\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "S1",
   "type": "stat",
   "description": "Percentage of product published at LTA vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "nb_lta_served", "id": "1", "type": "sum" }
     ],
     "query": "mission: S1 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    },
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected_lta_number", "id": "1", "type": "sum" }
     ],
     "query": "mission: S1 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S2",
   "type": "stat",
   "description": "Percentage of product published at LTA vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "nb_lta_served", "id": "1", "type": "sum" }
     ],
     "query": "mission: S2 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    },
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected_lta_number", "id": "1", "type": "sum" }
     ],
     "query": "mission: S2 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S3",
   "type": "stat",
   "description": "Percentage of product published at LTA vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "nb_lta_served", "id": "1", "type": "sum" }
     ],
     "query": "mission: S3 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    },
    {
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected_lta_number", "id": "1", "type": "sum" }
     ],
     "query": "mission: S3 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S5",
   "type": "stat",
   "description": "Percentage of product published at LTA vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Sum nb_lta_served",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S5 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    },
    {
     "alias": "Sum expected_lta_number",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S5 AND product_level:$product_level_lta AND product_type: $product_type_lta AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "Menu",
   "type": "text",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<ul>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Acquisition\">Acquisition</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Completeness\">Completeness</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Timeliness\">Timeliness</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Volumes and Count\">Volumes and Count</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=System Technical budget\">System Technical budget</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Unavailability\">Unavailability</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Anomalies\">Anomalies</a>\n        </div>\n    </li>\n    <li class=\"css-1kygs5l\">\n        <div class=\"css-1whfrzg\">\n                <a class=\"css-1nqqpiv\" href=\"/grafana/d/Uaq0mY57z/home?var-selected_tag=Monitoring\">Monitoring</a>\n        </div>\n    </li>\n</ul>"
   }
  },
  { "title": "${selected_tag}", "type": "dashlist", "gridPos": { "h": 18, "w": 12, "x": 4, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 5 },
   "options": {
    "content": "<center><p style=\"font-size:18px\">Dissemination Completeness</center></p> \r\n\r\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "S1",
   "type": "stat",
   "description": "Percentage of product published at DD vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "dd_prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S1 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: * AND dddas_publication_date:* ",
     "timeField": "prip_publication_date"
    },
    {
     "alias": "prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S1 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S2",
   "type": "stat",
   "description": "Percentage of product published at DD vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "dd_prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S2 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: * AND dddas_publication_date:* ",
     "timeField": "prip_publication_date"
    },
    {
     "alias": "prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S2 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S3",
   "type": "stat",
   "description": "Percentage of product published at DD vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "dd_prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S3 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: * AND dddas_publication_date:* ",
     "timeField": "prip_publication_date"
    },
    {
     "alias": "prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S3 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "title": "S5",
   "type": "stat",
   "description": "Percentage of product published at DD vs expected products to be published from PRIP\n\nTime Period (based on publication date at PRIP) : now-3d to now-4d (24h sliding window, 3 days in the past)",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "dd_prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S5 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: * AND dddas_publication_date:* ",
     "timeField": "prip_publication_date"
    },
    {
     "alias": "prip",
     "bucketAggs": [
      { "field": "prip_publication_date", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission: S5 AND product_level:$product_level_dd AND product_type: $product_type_dd AND prip_id: *",
     "timeField": "prip_publication_date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "options": {
    "content": "<center><p style=\"font-size:18px\">Production Completeness</center></p> \r\n"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "S1",
   "type": "stat",
   "description": "Completeness % for NRT & NRT-PT products only\n\nTime period \"Last day\" : now-3h - now-27h (sliding window of 24h)\n\n",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sensing_global_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission: S1 AND (timeliness: NRT OR timeliness: NRT-PT)",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "sensing_global_value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission: S1 AND (timeliness: NRT OR timeliness: NRT-PT)",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "S2",
   "type": "stat",
   "description": "Completeness % for all products\n\nTime period \"Last day\" : now-7h - now-31h (sliding window of 24h)\n\n",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "final_completeness_expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:S2",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "final_completeness_value", "id": "1", "type": "sum" }
     ],
     "query": "mission:S2",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "S3",
   "type": "stat",
   "description": "Completeness % for NR products only\n\nTime period \"Last day\" : now-3h - now-27h (sliding window of 24h)",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:S3 AND timeliness : NR",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:S3 AND timeliness : NR ",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "title": "S5",
   "type": "stat",
   "description": "Completeness % for NRTI products only\n\nTime period \"Last day\" : now-7h - now-31h \n\n(sliding window of 24h)\n",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "expected", "id": "1", "type": "sum" }
     ],
     "query": "mission:S5 AND timeliness : NRTI ",
     "timeField": "observation_time_start"
    },
    {
     "bucketAggs": [
      { "field": "observation_time_start", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value_adjusted", "id": "1", "type": "sum" }
     ],
     "query": "mission:S5 AND timeliness : NRTI",
     "timeField": "observation_time_start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 15 },
   "options": {
    "content": "<center><p style=\"font-size:18px\">Acquisition Completeness</center></p> "
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "EDRS",
   "type": "stat",
   "description": "Succesful passes (from EDRS daily reports / Planned passes)\n\nTime period : Yesterday ( between now-48h to now-24h)\n",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND report_name_daily: *",
     "timeField": "planned_link_session_start"
    },
    {
     "alias": "SumSuccessCount",
     "bucketAggs": [
      { "field": "planned_link_session_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "!total_status: \"NOK\" AND report_name_daily: *",
     "timeField": "planned_link_session_start"
    }
   ]
  },
  {
   "title": "X-Band",
   "type": "stat",
   "description": "The percentage of successful passes (from acquisition status published at Cadip, X-Band for S5) / Planned passes\n\nTime period \"Last day\" : now-3h - now-27h (sliding window of 24h)\n",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SumTotalCountNonS5",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "* AND NOT mission:S5",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumTotalCountS5",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:S5",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumSuccessCountNonS5",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "global_status: OK AND NOT mission:S5",
     "timeField": "planned_data_start"
    },
    {
     "alias": "SumSuccessCountS5",
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "antenna_status: OK AND front_end_status : OK AND delivery_push_status: OK AND mission:S5",
     "timeField": "planned_data_start"
    },
    { "expression": "$A+$B", "reducer": "sum", "type": "math" },
    { "expression": "$C+$D", "reducer": "sum", "type": "math" }
   ]
  }
 ]
}