{
 "title": "Dashboard usage",
 "tags": [ "Monitoring" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "Username",
    "query": "{\"find\": \"terms\", \"field\": \"user\",\"query\":\"*\"}"
   },
   {
    "name": "interface_name",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\",\"query\":\"*\"}"
   },
   {
    "name": "dashboard_title",
    "label": "Dashboard Title",
    "query": "{\"find\": \"terms\", \"field\": \"dashboard_title\",\"query\":\"*\"}"
   },
   {
    "name": "dashboard_id",
    "label": "Dashboard ID",
    "query": "{\"find\": \"terms\", \"field\": \"dashboard_uid\",\"query\":\"*\"}"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 most used dashboards",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dashboard_title",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface_name:$interface_name AND user:$user AND dashboard_uid:$dashboard_id AND dashboard_title:$dashboard_title ",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Top 10 less used dashboards",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dashboard_title",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface_name:$interface_name AND user:$user AND dashboard_uid:$dashboard_id AND dashboard_title:$dashboard_title ",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Nb of Grafana Dashboard Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "access_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "dashboard_uid:$dashboard_id AND dashboard_title:$dashboard_title AND interface_name:$interface_name AND user:$user",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Nb of Grafana Dashboard Access ( 1 month interval )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dashboard_title",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "access_date",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "dashboard_uid:$dashboard_id AND dashboard_title:$dashboard_title AND interface_name:$interface_name AND user:$user",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Distribution of the dashboards usage",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dashboard_title",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface_name:$interface_name AND user:$user AND dashboard_uid:$dashboard_id AND dashboard_title:$dashboard_title ",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Most Used Dashboards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "interface_name:$interface_name AND user:$user",
     "timeField": "access_date"
    }
   ]
  },
  {
   "title": "Least Used Dashboards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "interface_name:$interface_name AND user:$user",
     "timeField": "access_date"
    }
   ]
  }
 ]
}