{
 "title": "Interface monitoring Global view",
 "tags": [ "Monitoring" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interface_name",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\": \"interface_name\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Note:",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The name used to name the interfaces has been established by us for the collection.\nIt can lead to some confusion, considering that for each interface it is its catalog."
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "probe_time_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "probe_time_start"
    }
   ]
  },
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "This dashboard features an overview of the interfaces managed by OMCS.\n\nThe information displayed was originally taken from our Monitoring System  \n\nStatus is displayed with the following indicators:\n - A dashboard of interface with its status (green: OK, red: FAILED);\n - A detailed list of interface unavailability;\n - Timeline of interface status.\n\nEach interface is monitored through a periodic availability check.\n\nTime reference for this dashboard is : probe_time_start\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  },
  { "title": "Global Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "interface_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "status",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "interface_name: $interface_name ",
     "timeField": "probe_time_start"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last status ",
     "type": "table",
     "gridPos": { "h": 19, "w": 5, "x": 0, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "interface_name: $interface_name AND ingestionTime: [${__from:date} TO ${__to:date}]",
       "timeField": "probe_time_start"
      }
     ]
    },
    {
     "title": "Unavailability",
     "type": "table",
     "gridPos": { "h": 19, "w": 7, "x": 5, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "interface_name: $interface_name AND updateTime: [${__from:date} TO ${__to:date}] AND status: KO",
       "timeField": "status_time_start"
      }
     ]
    },
    {
     "title": "Number of unavailability >3h",
     "type": "table",
     "gridPos": { "h": 19, "w": 5, "x": 12, "y": 17 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "interface_name: $interface_name AND updateTime: [${__from:date} TO ${__to:date}] AND status: KO AND status_duration: [ 10800 TO *]",
       "timeField": "status_time_start"
      }
     ]
    },
    {
     "title": "Availability",
     "type": "gauge",
     "gridPos": { "h": 19, "w": 7, "x": 17, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface_name: $interface_name ",
       "timeField": "probe_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Status timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline status of interface",
     "type": "marcusolsson-gantt-panel",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "interface_name: $interface_name AND status_time_start: [ $__from TO *]",
       "timeField": "status_time_start"
      },
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "interface_name: $interface_name AND status_time_stop: [ * TO $__to ] AND status_time_start: [ * TO $__from]",
       "timeField": "status_time_stop"
      },
      {
       "columns": [
        { "selector": "_source.interface_name", "text": "interface_name", "type": "string" },
        { "selector": "_source.status", "text": "status", "type": "string" },
        { "selector": "_source.status_time_start", "text": "status_time_start", "type": "timestamp" },
        { "selector": "_source.status_time_stop", "text": "status_time_stop", "type": "timestamp" },
        { "selector": "_source.status_duration", "text": "status_duration", "type": "number" },
        { "selector": "_source.updateTime", "text": "updateTime", "type": "timestamp" }
       ],
       "root_selector": "hits",
       "source": "url",
       "type": "json",
       "url": "/cds-interface-status-monitoring/_search?q=interface_name:${interface_name:lucene}&size=1000",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Availability (for debug purpose)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability from consolidate activity",
     "type": "gauge",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "status_duration", "id": "1", "type": "sum" }
       ],
       "query": "interface_name: $interface_name AND status_time_stop: [ $__from TO * ]",
       "timeField": "status_time_start"
      },
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "status_duration", "id": "1", "type": "sum" }
       ],
       "query": "interface_name: $interface_name AND status_time_stop: [ * TO $__to ] AND status_time_start: [ * TO $__from]",
       "timeField": "status_time_stop"
      }
     ]
    },
    {
     "title": "Availability from raw-data-probe",
     "type": "gauge",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface_name: $interface_name ",
       "timeField": "probe_time_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Extended stats for interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of OK vs KO per interface",
     "type": "table",
     "gridPos": { "h": 20, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "status",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface_name: $interface_name ",
       "timeField": "probe_time_start"
      }
     ]
    },
    {
     "title": "Number of KO per interface",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 8, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "interface_name: $interface_name AND status: KO",
       "timeField": "probe_time_start"
      }
     ]
    },
    {
     "title": "Max probe duration per interface",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "2",
         "settings": {
          "min_doc_count": "0",
          "missing": "0",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "probe_duration",
         "id": "1",
         "settings": {},
         "type": "max"
        }
       ],
       "query": "interface_name: $interface_name AND status: KO",
       "timeField": "probe_time_start"
      }
     ]
    },
    {
     "title": "Number of KO per interface per day",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "interface_name",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "probe_time_start",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "4",
         "type": "count"
        }
       ],
       "query": "interface_name: $interface_name AND status: KO",
       "timeField": "probe_time_start"
      }
     ]
    }
   ]
  }
 ]
}