{
 "title": "Satellite Unavailability Reports",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mission",
    "label": "Mission",
    "query": "{\"find\":\"terms\",\"field\":\"mission\"}"
   },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\", \"query\":\"mission: $mission\"}"
   },
   {
    "name": "subsystem",
    "label": "Instrument",
    "query": "{\"find\":\"terms\",\"field\":\"subsystem\", \"query\":\"mission: $mission AND satellite_unit : $satellite_unit\"}"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features Satellite Unavailability report published at the following interface:\n - AUXIP.\n\nInformation is available for the following missions: S1 and S2."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Satellite Unavailability Report List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Satellite unavailability report list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem}",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Satellite Unavailability  Statistics for $satellite_unit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "satellite_unit",
   "targets": [
    {}
   ]
  },
  {
   "title": "${satellite_unit} Availability",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "missing": "0", "script": "_value / 1000000" }, "type": "sum" },
      {
       "id": "3",
       "pipelineVariables": [
        { "name": "var1" }
       ],
       "settings": { "script": "${__interval_ms} / 1000" },
       "type": "bucket_script"
      }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Total Unavail.",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "script": "_value/60000000" }, "type": "sum" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Longest Unavail.",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "script": "_value/60000000" }, "type": "max" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Instrument Longest Unavail.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "subsystem",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "script": "_value/60000000" }, "type": "max" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Instrument Total Unavail.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "subsystem",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "script": "_value/60000000" }, "type": "sum" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Instrument Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "subsystem",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "start_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "unavailability_duration", "id": "1", "settings": { "missing": "0", "script": "_value / 1000000" }, "type": "sum" },
      {
       "id": "3",
       "pipelineVariables": [
        { "name": "var1" }
       ],
       "settings": { "script": "${__interval_ms} / 1000" },
       "type": "bucket_script"
      }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "${satellite_unit} Subsystem Unavailability Timeline",
   "type": "marcusolsson-gantt-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "mission:${mission} AND satellite_unit:${satellite_unit} AND subsystem:${subsystem} AND unavailability_duration : *",
     "timeField": "start_time"
    }
   ]
  },
  {
   "title": "Alert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Satellite Unavailability Count All",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "start_time", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "start_time"
      }
     ]
    }
   ]
  }
 ]
}