{
 "title": "LTA Alignement",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "lta",
    "label": "LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\", \"query\": \"service_type: LTA  AND mission: $mission\"}"
   },
   {
    "name": "all_lta",
    "label": "ALL LTA Service",
    "query": "{\"find\": \"terms\", \"field\": \"service_id\", \"query\": \"service_type: LTA  AND mission: $mission\"}"
   },
   {
    "name": "product_level",
    "label": "Product Level",
    "query": "{\"find\": \"terms\", \"field\": \"product_level\",\"query\":\"mission: ${mission}\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\": \"terms\", \"field\": \"product_type\",\"query\":\"mission: ${mission} AND product_level:${product_level}\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a comparison of archived product on all LTA\n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  { "title": "LTA Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Production per LTA per publication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Acri",
     "bucketAggs": [
      { "field": "LTA_Acri_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Acri_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Werum",
     "bucketAggs": [
      { "field": "LTA_Werum_publication_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Werum_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Cloudferro",
     "bucketAggs": [
      {
       "field": "LTA_CloudFerro_publication_date",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_CloudFerro_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Exprivia S1",
     "bucketAggs": [
      {
       "field": "LTA_Exprivia_S1_publication_date",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Exprivia_S1_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Exprivia S2",
     "bucketAggs": [
      {
       "field": "LTA_Exprivia_S2_publication_date",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Exprivia_S2_is_published: true ",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Exprivia S3",
     "bucketAggs": [
      {
       "field": "LTA_Exprivia_S3_publication_date",
       "id": "2",
       "settings": { "interval": "auto" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Exprivia_S3_is_published: true",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Production per LTA per sensing",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Acri",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Acri_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Exprivia",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND (LTA_Exprivia_S1_is_published: true OR LTA_Exprivia_S2_is_published: true OR LTA_Exprivia_S3_is_published: true)",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Werum",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_Werum_is_published: true",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Cloudferro",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND product_type: $product_type AND product_level: $product_level AND LTA_CloudFerro_is_published: true",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "$all_lta",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "repeat": "all_lta",
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${all_lta}_is_published: true OR LTA_${all_lta}_S1_is_published: true OR LTA_${all_lta}_S2_is_published: true OR LTA_${all_lta}_S3_is_published: true ) AND product_type: $product_type AND product_level: $product_level",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "$all_lta",
   "type": "barchart",
   "gridPos": { "h": 30, "w": 6, "x": 0, "y": 28 },
   "repeat": "all_lta",
   "targets": [
    {
     "alias": "Archived",
     "bucketAggs": [
      {
       "field": "product_type",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${all_lta}_is_published: true OR LTA_${all_lta}_S1_is_published: true OR LTA_${all_lta}_S2_is_published: true OR LTA_${all_lta}_S3_is_published: true ) AND product_type: $product_type AND product_level: $product_level",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Detailed LTA Completeness ($lta)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "lta",
   "collapsed": true,
   "panels": [
    {
     "title": "Products Published by at least one LTA",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND product_type: $product_type AND product_level:$product_level AND nb_lta_served: [1 TO *]",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Products Archived by LTA",
     "type": "stat",
     "description": "Total Archived Products by LTA and also published @AUXIP",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) AND product_type: $product_type",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived Products",
     "type": "stat",
     "description": "Published @AUXIP but NOT @LTA",
     "gridPos": { "h": 4, "w": 5, "x": 11, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "Not archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type: $product_type AND nb_lta_served: [1 TO *] AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) ",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Percentage of Archived products LTA",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND product_type: $product_type AND product_level:$product_level AND nb_lta_served: [1 TO *]",
       "timeField": "sensing_start_date"
      },
      {
       "alias": "Not Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type: $product_type AND nb_lta_served: [1 TO *] AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived products over time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "Not Archived",
       "bucketAggs": [
        { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type: $product_type AND nb_lta_served: [1 TO *] AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) ",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived Products List",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type: $product_type AND nb_lta_served: [1 TO *] AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Archived products per product type",
     "type": "barchart",
     "gridPos": { "h": 24, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        {
         "field": "mission",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )\nAND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "Not Archived products per product type",
     "type": "barchart",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "alias": "Archived",
       "bucketAggs": [
        {
         "field": "mission",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "product_type",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "satellite_unit : $satellite AND mission: $mission AND product_level:$product_level AND product_type: $product_type AND nb_lta_served: [1 TO *] AND NOT (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true ) ",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": "List of Archived Products",
     "type": "table",
     "description": "Total Archived Products by LTA and also published @AUXIP",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "mission: $mission AND satellite_unit : $satellite AND (LTA_${lta}_is_published: true OR LTA_${lta}_S1_is_published: true OR LTA_${lta}_S2_is_published: true OR LTA_${lta}_S3_is_published: true )\nAND product_type: $product_type AND (prip_id: * OR auxip_id: * OR (mission:S5 AND product_level:L0_))",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}