{
 "title": "Acquisition Timeliness",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\": \"terms\", \"field\": \"satellite_unit\",\"query\":\"mission: ${mission}\"}"
   },
   { "name": "ground_station", "label": "Reception Station", "query": "INS,INU,MPS,MTI,NSG,SGS" },
   {
    "name": "cams_ids",
    "label": "CAMS Ticket",
    "query": "{\"find\": \"terms\", \"field\": \"key\",\"query\":\"acquisition_pass:*\"}"
   },
   {
    "name": "downlink_orbit_ddp",
    "label": "Downlink Orbit DDP",
    "query": "{\"find\": \"terms\", \"field\": \"downlink_orbit\",\"query\":\"mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station\"}"
   },
   {
    "name": "downlink_orbit_cadip",
    "label": "Downlink Orbit Cadip",
    "query": "{\"find\": \"terms\", \"field\": \"downlink_orbit\",\"query\":\"mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features an Acquisition Timeliness for Mission S1, S2, S3, S5.\n\nInformation is taken from station reports made available through CADIP interface for S1,S2,S3 and XBAND for S5\n\n\nTimeliness is computed using following logics : \n- (stop_delivery date - first_frame_start date) for mission S1,S2 and S3\n- (delivery_stop date - downlink_start date) for mission S5\n\nDiscrepancies are displayed through the following indicators:\n\n- Percent of products below timeliness threshold;\n- Average timeliness of products;\n- Time series of product displayed against the timeliness threshold;\n- Detailed list of product out of accepted range.\n\nTips:\n - Annotations are available on time series;\n - Satellite, mission, reception station or downlink orbit to consider can be selected in the upper bar.\n- Use Downlink Orbit Cadip to filter the downlink orbit for mission S1,S2 and S3\n- Use Downlink Orbit DDP to filter the downlink orbit for mission S5\n\nThe information displayed was originally taken from Session with Quality Infos at each CADIP station and from EDRS Report Ticket at JIRA EDRS  \n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view.\n\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Acquisition Timeliness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timeliness ( < 60min )",
   "type": "gauge",
   "description": "1h",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "less_1H_ddp",
     "bucketAggs": [
      {
       "field": "first_frame_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 3600000000] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)\n",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_ddp",
     "bucketAggs": [
      { "field": "first_frame_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "less_1H_cadip",
     "bucketAggs": [
      {
       "field": "downlink_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 3600000000] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "bucketAggs": [
      { "field": "downlink_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Timeliness ( < 75min )",
   "type": "gauge",
   "description": " 1h15",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "less_1H_ddp",
     "bucketAggs": [
      {
       "field": "first_frame_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 4500000000] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)\n",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_ddp",
     "bucketAggs": [
      { "field": "first_frame_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "less_1H_cadip",
     "bucketAggs": [
      {
       "field": "downlink_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 4500000000] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "bucketAggs": [
      { "field": "downlink_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND from_acq_delivery_timeliness:*  AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Min timeliness acquisition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "type": "min" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "type": "min" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Acquisition Timeliness Over Time",
   "type": "timeseries",
   "description": "Data reaching the top of the chart exceeds 120 minutes (2h)",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "less_1H_ddp",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Avg timeliness acquisition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "settings": { "script": "_value / 60000000" }, "type": "avg" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "settings": { "script": "_value / 60000000" }, "type": "avg" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Timeliness ( < 90min )",
   "type": "gauge",
   "description": "1h30",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "less_1H_ddp",
     "bucketAggs": [
      {
       "field": "first_frame_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 5400000000] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)\n",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_ddp",
     "bucketAggs": [
      { "field": "first_frame_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "less_1H_cadip",
     "bucketAggs": [
      {
       "field": "downlink_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 5400000000] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "bucketAggs": [
      { "field": "downlink_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Timeliness ( < 105min )",
   "type": "gauge",
   "description": "1h45",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "less_1H_ddp",
     "bucketAggs": [
      {
       "field": "first_frame_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 6300000000] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)\n",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_ddp",
     "bucketAggs": [
      { "field": "first_frame_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "less_1H_cadip",
     "bucketAggs": [
      {
       "field": "downlink_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [0 TO 6300000000] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "bucketAggs": [
      { "field": "downlink_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Max timeliness acquisition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "type": "max" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "bucketAggs": [
      { "field": "planned_data_start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "from_acq_delivery_timeliness", "id": "1", "type": "max" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Timeliness ( > 105min )",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "less_3H_ddp",
     "bucketAggs": [
      {
       "field": "first_frame_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [6300000000 TO *] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit: $downlink_orbit_ddp ",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_ddp",
     "bucketAggs": [
      { "field": "first_frame_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit: $downlink_orbit_ddp AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "less_3H_cadip",
     "bucketAggs": [
      {
       "field": "downlink_start",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_acq_delivery_timeliness: [6300000000 TO *] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit: $downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "total_cadip",
     "bucketAggs": [
      { "field": "downlink_start", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit: $downlink_orbit_cadip AND from_acq_delivery_timeliness:* AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "StdDev timeliness acquisition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "All acquisition",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "< 3h",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  },
  {
   "title": "Out of timeliness acquisition ( > 60min )",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "< 3h",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "from_acq_delivery_timeliness: [3600000000 TO *] AND mission:$mission AND satellite_id:$satellite_unit AND mission:S5 AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_ddp AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    },
    {
     "alias": "< 3h",
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "from_acq_delivery_timeliness: [3600000000 TO *] AND mission:$mission AND satellite_id:$satellite_unit AND ground_station:$ground_station AND downlink_orbit:$downlink_orbit_cadip AND (cams_tickets: $cams_ids)",
     "timeField": "planned_data_start"
    }
   ]
  }
 ]
}