{
 "title": "ADG Timeliness - v2",
 "description": "v2 with feature group by prodivers",
 "tags": [ "Timeliness" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3" },
   {
    "name": "satellite_unit",
    "label": "Satellite",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\", \"query\":\"mission: $mission AND service_type:AUXIP\"}"
   },
   {
    "name": "product_type_per_producer_",
    "label": "Auxilliary Data Provider",
    "query": "All : *,CAMS : (AUX_CAMSFO),EUMETSAT (ECMWF) : (AUX_WND OR AUX_ECMWFD OR AX___MF1_AX OR AX___MFA_AX OR AX___MA1_AX OR AX___MF2_AX OR AX___MA2_AX OR AUX_ICE OR AUX_TRO),EUMETSAT (MET Office) : (SL_2_SSTAAX),EUMETSAT (SALP) : (SR_2_PMPSAX OR SR_2_POL_AX OR SR_2_PGI_AX OR SR_2_RGI_AX OR SR_1_USO_AX OR SR___MGNSAX OR SR_2_RMO_AX OR SR_2_PMO_AX),EUMETSAT (NOAA) : (SL_2_DIMSAX),FOS : (MPL_ORBPRE OR MPL_ORBRES OR MPL_TLEPRE OR TLM__REQ_B OR TLM__REQ_C OR TLM__REQ_D OR TLM__REQ_E OR TLM__REQ_F OR TLM__REQ_A OR TLM__REQ_B OR REP__CHF__ OR REP__FCHF_ OR AX___FPO_AX OR AX___FRO_AX),IERS : (AUX_UT1UTC),OSI SAF : (SR_2_SIFNAX OR SR_2_SIFSAX OR SR_2_SICNAX OR SR_2_SICSAX),POD : (SR_2_PCPPAX OR SR_2_PMPPAX OR SR___MGNPAX OR SR___POEPAX OR AUX_GNSSRD OR AUX_PREORB OR AUX_RESORB OR AUX_POEORB)"
   },
   { "name": "Filter", "label": "Ad-Hoc filter" },
   {
    "name": "S1_30",
    "query": "AUX_WND,MPL_GTDEV,MPL_ORBPRE ,MPL_ORBRES,MPL_TLEPRE,TLM_REQ_B,TLM_REQ_D,TLM_REQ_E,TLM_REQ_F,AUX_PREORB,AUX_RESORB,AUX_POEORB"
   },
   {
    "name": "S1_10",
    "query": "AUX_ICE,AMH_ERRMAT,AMV_ERRMA,TLM_REQ_C"
   },
   {
    "name": "product_type_several_per_day",
    "query": "AUX_WND,AUX_PREORB,AUX_RESORB,AUX_POEORB,AUX_ECMWFD,AX___MF1_AX,AX___MFA_AX,AX___MA1_AX,AX___MF2_AX,AX___MA2_AX,SR___MDO_AX,SR_2_RMO_AX,SR_2_PMO_AX"
   },
   {
    "name": "product_type_once_per_day",
    "query": "AUX_ICE,AUX_TRO,MPL_ORBPRE,MPL_ORBRES,MPL_TLEPRE,TLM__REQ_B,TLM__REQ_C,TLM__REQ_D,TLM__REQ_E,TLM__REQ_F,AUX_CAMSFO,AUX_UT1UTC,TLM__REQ_A,REP__CHF__,REP__FCHF_,SR_2_PMPSAX,SR_2_POL_AX,SR_2_PGI_AX,SR_2_RGI_AX,SR_1_USO_AX,SR___MGNSAX,SL_2_SSTAAX,SL_2_DIMSAX,AX___FPO_AX,AX___FRO_AX,AUX_POEORB,AUX_GNSSRD,SR_2_PCPPAX,SR_2_PMPPAX,SR___MGNPAX,SR___POEPAX,SR_2_SIFNAX,SR_2_SIFSAX"
   },
   { "name": "auxiliary_data_providers", "label": "Auxiliary Data Providers", "query": { "query": "" } },
   { "name": "product_types", "label": "Product Types", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard features a Timeliness computation of data published at the following interfaces:\n - AUXIP.\n\nAuxiliary data is divided into two categories:\n - Several per day (timeliness should be below 10 minutes);\n - One per day (timeliness should be below 30 minutes).\n\nThe list of products and their associated frequency :\n\n| Timeliness                | Product Type                                                                                                                                                                                                                                                                                                                                                                                                                                              |\n|---------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|\n| Several per day (<10 min) | AUX_WND, AUX_PREORB, AUX_RESORB, AUX_POEORB, AUX_ECMWFD, AX___MF1_AX, AX___MFA_AX, AX___MA1_AX, AX___MF2_AX, AX___MA2_AX, SR___MDO_AX, SR_2_RMO_AX, SR_2_PMO_AX                                                                                                                                                                                                                                                                                           |\n| One per day (<30 min)     | AUX_ICE, AUX_TRO, MPL_ORBPRE, MPL_ORBRES, MPL_TLEPRE, TLM__REQ_B, TLM__REQ_C, TLM__REQ_D, TLM__REQ_E, TLM__REQ_F, AUX_CAMSFO, AUX_UT1UTC, TLM__REQ_A, TLM__REQ_B, REP__CHF__, REP__FCHF_, MPL_ORBPRE, MPL_ORBRES, SR_2_PMPSAX, SR_2_POL_AX, SR_2_PGI_AX, SR_2_RGI_AX, SR_1_USO_AX, SR___MGNSAX, SL_2_SSTAAX, SL_2_DIMSAX, AX___FPO_AX, AX___FRO_AX, AUX_POEORB, AUX_GNSSRD, SR_2_PCPPAX, SR_2_PMPPAX, SR___MGNPAX, SR___POEPAX, SR_2_SIFNAX, SR_2_SIFSAX |\n\nTimeliness is computed from metadata attached to each Auxiliary data (Publication Date - Origin Date).\n\nDiscrepancies are displayed through the following indicators:\n - Percent of data below timeliness threshold;\n - Average timeliness of data;\n - Time series of data displayed against the timeliness threshold;\n - Detailed list of data out of accepted range.\n\nInformation is available for each mission managed by OMCS.\n\nTips:\n - Annotations are available on time series;\n - Mission to consider can be selected in the upper bar.\n\n\nThe information displayed was originally taken from Product at AUXIP  \n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "ADG Timeliness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "\"Several per day\" Timeliness (< 10 min)",
   "type": "gauge",
   "description": "Timeliness for files published several times per day ",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "10 min",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "transfer_timeliness: [0 TO 600000000] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_several_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_several_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"Several per day\" average timeliness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "avg" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_several_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"Several per day\" timeliness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Timeliness",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "max" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_several_per_day:lucene} AND product_type : ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" timeliness (< 30 min)",
   "type": "gauge",
   "description": "Timeliness for files published once or less than once per day",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "30 min",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "transfer_timeliness: [0 TO 1800000000] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_once_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_once_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" average timeliness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "avg" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_once_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "\"One per day\" timeliness over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Timeliness",
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "transfer_timeliness", "id": "1", "type": "max" }
     ],
     "query": "service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type:${product_type_once_per_day:lucene} AND product_type: ${product_types:lucene}",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Out of timeliness product list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Out of timeliness products (several per day)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "< 3h",
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": "transfer_timeliness: [600000000 TO *] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: ${product_types:lucene}",
       "timeField": "sensing_start_date"
      }
     ]
    },
    {
     "title": " Out of timeliness products (one per day)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "< 3h",
       "metrics": [
        { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
       ],
       "query": " transfer_timeliness: [1800000000 TO *] AND service_type : AUXIP AND mission:${mission} AND satellite_unit:${satellite_unit} AND product_type: ${product_types:lucene}",
       "timeField": "sensing_start_date"
      }
     ]
    }
   ]
  }
 ]
}