{
 "title": "DD Timeliness",
 "tags": [ "Timeliness" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mission", "label": "Mission", "query": "S1,S2,S3,S5" },
   {
    "name": "satellite",
    "label": "Satellite",
    "query": "{\"find\":\"terms\",\"field\":\"satellite_unit\",  \"query\":\"mission: $mission\"}"
   },
   {
    "name": "timeliness",
    "label": "Category",
    "query": "{\"find\": \"terms\", \"field\": \"timeliness\",\"query\":\"mission: ${mission} \"}"
   },
   {
    "name": "product_level",
    "label": "Level",
    "query": "{\"find\":\"terms\",\"field\":\"product_level\", \"query\":\"mission: $mission AND satellite_unit : $satellite\"}"
   },
   {
    "name": "product_type",
    "label": "Product Type",
    "query": "{\"find\":\"terms\",\"field\":\"product_type\", \"query\":\"mission: $mission AND satellite_unit : $satellite AND product_level:$product_level\"}"
   },
   { "name": "dd_service", "label": "DD Service", "query": "ddip,dddas" },
   { "name": "Filter", "label": "Ad-Hoc filter" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# DDs Timeliness\nThis dashboard show statistics about the DD product timeliness.\n\nThe information displayed was originally taken from Product at DD  \n\nTime reference for this dashboard is : sensing_start_date\n\nImportant notice : Tables & timelines can only display up to 10 000 entries. Please make use of filters to narrow down the retrieved data and get a more realistic view."
     }
    }
   ]
  },
  { "title": "DD Timeliness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Timeliness 0-3 days",
   "type": "gauge",
   "description": "Number of product with timeliness between 0 and 3 days ",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sensing_start_date",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: [0 TO 259200000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Timeliness 3-5 days",
   "type": "gauge",
   "description": "Number of product with timeliness between 3 and 5 days ",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {259200000000 TO 432000000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Timeliness 5-15 days",
   "type": "gauge",
   "description": "Number of product with timeliness between 5 and 15 days ",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {432000000000 TO 1296000000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness \n",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Timeliness > 15 days",
   "type": "gauge",
   "description": "Number of product with timeliness more than 15 days ",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {1296000000000 TO *] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness \n",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Timeliness distribution ",
   "type": "piechart",
   "description": "Number of product and percentage with timeliness between 0-3 days / 3-5 days / 5-15 days / above 15 days ",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "0 - 3 days",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: [0 TO 259200000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "3 - 5 days",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {259200000000 TO 432000000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "5 - 15 days",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {432000000000 TO 1296000000000] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    },
    {
     "alias": "Above 15 days",
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {1296000000000 TO *] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Average timeliness on period",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "from_prip_${dd_service}_timeliness",
       "id": "1",
       "settings": { "missing": "0", "script": "_value/60000000" },
       "type": "avg"
      }
     ],
     "query": "prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Max timeliness on period",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "sensing_start_date", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "from_prip_${dd_service}_timeliness",
       "id": "1",
       "settings": { "script": "_value/60000000" },
       "type": "max"
      }
     ],
     "query": "prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness",
     "timeField": "sensing_start_date"
    }
   ]
  },
  {
   "title": "Product with timeliness above 3 days",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "from_prip_${dd_service}_timeliness: {259200000000 TO *] AND prip_id: * AND mission:$mission AND satellite_unit:$satellite AND product_level:$product_level AND product_type:$product_type AND timeliness:$timeliness ",
     "timeField": "sensing_start_date"
    }
   ]
  }
 ]
}